"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, BrainCircuit } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SisagDataState, SisagPage, SisagPageHeader } from "@/components/sisag";

type Data = {
  summary: { acceptanceRate: number; agreementRate: number; averageConfidence: number; averageReviewMinutes: number; pending: number; reviewed: number; accepted: number; adjusted: number; rejected: number };
  agent: { executions: number; aiRuns: number; fallbackRuns: number; aiRate: number; fallbackRate: number; agentDeterministicAgreementRate: number; agentHumanAgreementRate: number; humanComparisons: number; inputTokens: number; outputTokens: number; totalTokens: number; averageDurationMs: number; p95DurationMs: number };
  retrieval: { executions:number; vectorRuns:number; fallbackRuns:number; availabilityRate:number; fallbackRate:number; averageOverlapRate:number; totalTokens:number; averageTokens:number; averageDurationMs:number; p95DurationMs:number; errors:Array<{errorCode:string;count:number}>; humanEvaluation:{lexical:{evaluations:number;relevanceScore:number;precisionAt1:number};vector:{evaluations:number;relevanceScore:number;precisionAt1:number};delta:number;pairedRecommendations:number;vectorWins:number;lexicalWins:number;ties:number}; qualityGate:{status:"insufficient_data"|"keep_shadow"|"eligible";policyVersion:string;automaticPromotion:false;interpretation:string;humanEvidenceNote:string;sample:{executions:number;humanComparisons:number;vectorEvaluations:number};checks:Array<{code:string;passed:boolean;actual:number;operator:"gte"|"lte";threshold:number;evidence:"retrieval"|"workflow_correlation"}>;reasons:string[]} };
  providers: Array<{ provider: string; model: string; total: number; aiRuns: number; fallbackRuns: number; averageDurationMs: number; totalTokens: number }>;
  errors: Array<{ errorCode: string; count: number }>;
};

export default function Page() {
  const [data, setData] = useState<Data | null>(null), [days, setDays] = useState(30), [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); const response = await fetch("/api/v1/settings/booking-followups/recovery/agent-outcomes?days=" + days, { cache: "no-store" }); setData(response.ok ? await response.json() : null); setLoading(false); }, [days]);
  useEffect(() => { void load(); }, [load]);
  return <SisagPage>
    <SisagPageHeader context={<span className="inline-flex items-center gap-2"><BrainCircuit className="h-4 w-4" />Inteligência assistida</span>} title="Qualidade do agente em sombra" description="Compare agente, regras e decisões humanas antes de ampliar qualquer autonomia." />
    <div className="flex flex-wrap justify-between gap-2"><div className="flex flex-wrap gap-2"><Button asChild variant="ghost" size="sm"><Link href="/admin/settings/booking-followups/recovery"><ArrowLeft className="mr-2 h-4 w-4" />Voltar aos casos</Link></Button><Button asChild variant="outline" size="sm"><Link href="/admin/settings/booking-followups/recovery/retrieval-evaluation">Avaliar retrieval</Link></Button><Button asChild variant="outline" size="sm"><Link href="/admin/settings/booking-followups/recovery/agent-outcomes/baselines">Gerenciar baselines</Link></Button><Button asChild variant="outline" size="sm"><Link href="/admin/settings/booking-followups/recovery/agent-outcomes/regression">Comparar regressões</Link></Button></div><div className="flex gap-2">{[7, 30, 90].map(value => <Button key={value} size="sm" variant={days === value ? "default" : "outline"} onClick={() => setDays(value)}>{value} dias</Button>)}</div></div>
    {loading ? <SisagDataState state="loading" title="Calculando qualidade" /> : data ? <>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Execuções por IA" value={`${data.agent.aiRate}%`} detail={`${data.agent.aiRuns}/${data.agent.executions}`} /><Metric label="Fallback seguro" value={`${data.agent.fallbackRate}%`} detail={`${data.agent.fallbackRuns}/${data.agent.executions}`} /><Metric label="Agente × humano" value={`${data.agent.agentHumanAgreementRate}%`} detail={`${data.agent.humanComparisons} comparações`} /><Metric label="Agente × regras" value={`${data.agent.agentDeterministicAgreementRate}%`} /></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Tokens consumidos" value={data.agent.totalTokens.toLocaleString("pt-BR")} detail={`${data.agent.inputTokens} entrada · ${data.agent.outputTokens} saída`} /><Metric label="Duração média" value={`${data.agent.averageDurationMs} ms`} /><Metric label="Duração p95" value={`${data.agent.p95DurationMs} ms`} /><Metric label="Aceitação humana" value={`${data.summary.acceptanceRate}%`} detail={`Regras × humano: ${data.summary.agreementRate}%`} /></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Busca vetorial sombra" value={`${data.retrieval.vectorRuns}/${data.retrieval.executions}`} /><Metric label="Sobreposição com lexical" value={`${data.retrieval.averageOverlapRate}%`} /><Metric label="Tokens de embeddings" value={data.retrieval.totalTokens.toLocaleString("pt-BR")} /><Metric label="Latência de embeddings" value={`${data.retrieval.averageDurationMs} ms`} /></div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Relevância lexical humana" value={`${data.retrieval.humanEvaluation.lexical.relevanceScore}%`} detail={`${data.retrieval.humanEvaluation.lexical.evaluations} avaliações`} /><Metric label="Relevância vetorial humana" value={`${data.retrieval.humanEvaluation.vector.relevanceScore}%`} detail={`${data.retrieval.humanEvaluation.vector.evaluations} avaliações`} /><Metric label="Delta vetorial × lexical" value={`${data.retrieval.humanEvaluation.delta} p.p.`} detail={`${data.retrieval.humanEvaluation.pairedRecommendations} casos pareados`} /><Metric label="Vitórias vetoriais" value={`${data.retrieval.humanEvaluation.vectorWins}`} detail={`${data.retrieval.humanEvaluation.lexicalWins} lexicais · ${data.retrieval.humanEvaluation.ties} empates`} /></div>
      <Card className="rounded-2xl"><CardHeader><CardTitle className="flex flex-wrap items-center justify-between gap-2 text-lg">Gate de qualidade do retrieval <span className={data.retrieval.qualityGate.status==="eligible"?"rounded-full bg-emerald-100 px-3 py-1 text-xs text-emerald-800":"rounded-full bg-amber-100 px-3 py-1 text-xs text-amber-800"}>{data.retrieval.qualityGate.status==="eligible"?"Elegível para revisão humana":data.retrieval.qualityGate.status==="keep_shadow"?"Manter em sombra":"Dados insuficientes"}</span></CardTitle></CardHeader><CardContent><p className="text-sm text-slate-600">Política {data.retrieval.qualityGate.policyVersion} · {data.retrieval.qualityGate.sample.executions} execuções · {data.retrieval.qualityGate.sample.humanComparisons} comparações humanas. Nenhuma promoção é automática.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.retrieval.qualityGate.checks.map(check=><div key={check.code} className={check.passed?"rounded-xl bg-emerald-50 p-3 text-sm":"rounded-xl bg-amber-50 p-3 text-sm"}><b>{check.code}</b><p className="text-xs text-slate-600">observado {check.actual} · limite {check.operator==="gte"?"mín.":"máx."} {check.threshold}</p></div>)}</div><p className="mt-3 text-xs text-slate-500">A concordância humana é apenas um sinal correlacional do fluxo, não um rótulo de relevância vetorial.</p></CardContent></Card>
      <Card className="rounded-2xl"><CardHeader><CardTitle className="text-lg">Provedores e modelos</CardTitle></CardHeader><CardContent>{data.providers.length ? data.providers.map(item => <div key={`${item.provider}:${item.model}`} className="mb-2 rounded-xl bg-slate-50 p-3 text-sm"><b>{item.provider} · {item.model}</b><p className="mt-1 text-slate-600">{item.total} execuções · {item.aiRuns} IA · {item.fallbackRuns} fallback · {item.totalTokens} tokens · média {item.averageDurationMs} ms</p></div>) : <p className="text-sm text-slate-500">Nenhuma execução registrada no período.</p>}</CardContent></Card>
      <Card className="rounded-2xl"><CardHeader><CardTitle className="text-lg">Falhas normalizadas</CardTitle></CardHeader><CardContent>{data.errors.length ? <div className="grid gap-2 sm:grid-cols-2">{data.errors.map(item => <div key={item.errorCode} className="rounded-xl bg-amber-50 p-3 text-sm"><b>{item.errorCode}</b> · {item.count}</div>)}</div> : <p className="text-sm text-emerald-700">Nenhuma falha registrada no período.</p>}</CardContent></Card>
    </> : <SisagDataState state="empty" title="Sem dados de recomendações" />}
  </SisagPage>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail?: string }) { return <div className="rounded-xl border bg-white p-4"><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-slate-500">{label}</p>{detail ? <p className="mt-1 text-xs text-slate-400">{detail}</p> : null}</div>; }
