import { and, desc, eq, gt, lt } from "drizzle-orm";
import { availabilityExceptions, companyUnits, professionals, professionalUnits } from "@/drizzle/schema";
import { getDb } from "@/lib/db";
import type { AvailabilityExceptionFilter, AvailabilityExceptionInput } from "./AvailabilityException.schema";
export class AvailabilityExceptionError extends Error { constructor(public code: "unit_not_found" | "professional_not_found" | "professional_unit_not_linked" | "exception_not_found") { super(code); } }
export type AvailabilityExceptionItem = { id: string; kind: string; unitId: string | null; unitName: string | null; professionalId: string | null; professionalName: string | null; startsAt: Date; endsAt: Date; allDay: boolean; reason: string; status: string; createdBy: string | null; revokedAt: Date | null; revokedBy: string | null; createdAt: Date };
type Dependencies = { list?: (companyId: string, filter: AvailabilityExceptionFilter) => Promise<AvailabilityExceptionItem[]>; create?: (companyId: string, userId: string, input: AvailabilityExceptionInput) => Promise<AvailabilityExceptionItem>; revoke?: (companyId: string, userId: string, id: string) => Promise<AvailabilityExceptionItem> };
const boundary = (companyId: string, userId?: string) => { if (!companyId.trim()) throw new Error("missing_company_id"); if (userId !== undefined && !userId.trim()) throw new Error("missing_user_id"); };
const selection = { id: availabilityExceptions.id, kind: availabilityExceptions.kind, unitId: availabilityExceptions.unitId, unitName: companyUnits.name, professionalId: availabilityExceptions.professionalId, professionalName: professionals.name, startsAt: availabilityExceptions.startsAt, endsAt: availabilityExceptions.endsAt, allDay: availabilityExceptions.allDay, reason: availabilityExceptions.reason, status: availabilityExceptions.status, createdBy: availabilityExceptions.createdBy, revokedAt: availabilityExceptions.revokedAt, revokedBy: availabilityExceptions.revokedBy, createdAt: availabilityExceptions.createdAt };
async function listInDatabase(companyId: string, filter: AvailabilityExceptionFilter) { const conditions = [eq(availabilityExceptions.companyId, companyId)]; if (filter.status !== "all") conditions.push(eq(availabilityExceptions.status, filter.status)); if (filter.unitId) conditions.push(eq(availabilityExceptions.unitId, filter.unitId)); if (filter.professionalId) conditions.push(eq(availabilityExceptions.professionalId, filter.professionalId)); if (filter.from) conditions.push(gt(availabilityExceptions.endsAt, new Date(filter.from))); if (filter.to) conditions.push(lt(availabilityExceptions.startsAt, new Date(filter.to))); return getDb().select(selection).from(availabilityExceptions).leftJoin(companyUnits, and(eq(companyUnits.companyId, companyId), eq(companyUnits.id, availabilityExceptions.unitId))).leftJoin(professionals, and(eq(professionals.companyId, companyId), eq(professionals.id, availabilityExceptions.professionalId))).where(and(...conditions)).orderBy(desc(availabilityExceptions.startsAt), desc(availabilityExceptions.createdAt)); }
async function createInDatabase(companyId: string, userId: string, input: AvailabilityExceptionInput) { return getDb().transaction(async (tx) => { if (input.unitId) { const unit = await tx.select({ id: companyUnits.id }).from(companyUnits).where(and(eq(companyUnits.companyId, companyId), eq(companyUnits.id, input.unitId), eq(companyUnits.active, true))).limit(1); if (!unit[0]) throw new AvailabilityExceptionError("unit_not_found"); } if (input.professionalId) { const professional = await tx.select({ id: professionals.id }).from(professionals).where(and(eq(professionals.companyId, companyId), eq(professionals.id, input.professionalId))).limit(1); if (!professional[0]) throw new AvailabilityExceptionError("professional_not_found"); if (input.unitId) { const link = await tx.select({ id: professionalUnits.id }).from(professionalUnits).where(and(eq(professionalUnits.companyId, companyId), eq(professionalUnits.professionalId, input.professionalId), eq(professionalUnits.unitId, input.unitId), eq(professionalUnits.active, true))).limit(1); if (!link[0]) throw new AvailabilityExceptionError("professional_unit_not_linked"); } } const rows = await tx.insert(availabilityExceptions).values({ companyId, unitId: input.unitId ?? null, professionalId: input.professionalId ?? null, kind: input.kind, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), allDay: input.allDay, reason: input.reason, status: "active", createdBy: userId }).returning(); const row = rows[0]!; return { ...row, unitName: null, professionalName: null }; }); }
async function revokeInDatabase(companyId: string, userId: string, id: string) { const rows = await getDb().update(availabilityExceptions).set({ status: "revoked", revokedAt: new Date(), revokedBy: userId, updatedAt: new Date() }).where(and(eq(availabilityExceptions.companyId, companyId), eq(availabilityExceptions.id, id), eq(availabilityExceptions.status, "active"))).returning(); const row = rows[0]; if (!row) throw new AvailabilityExceptionError("exception_not_found"); return { ...row, unitName: null, professionalName: null }; }
export async function listAvailabilityExceptions(companyId: string, filter: AvailabilityExceptionFilter, dependencies: Dependencies = {}) { boundary(companyId); return (dependencies.list ?? listInDatabase)(companyId, filter); }
export async function createAvailabilityException(companyId: string, userId: string, input: AvailabilityExceptionInput, dependencies: Dependencies = {}) { boundary(companyId, userId); return (dependencies.create ?? createInDatabase)(companyId, userId, input); }
export async function revokeAvailabilityException(companyId: string, userId: string, id: string, dependencies: Dependencies = {}) { boundary(companyId, userId); return (dependencies.revoke ?? revokeInDatabase)(companyId, userId, id); }
