import { and, desc, eq, inArray, lt, gt, sql } from "drizzle-orm";
import { availabilityExceptions, professionals, professionalUnits } from "@/drizzle/schema";
import { getDb } from "@/lib/db";
export type BlockingException = { professionalId: string | null; unitId: string | null; startsAt: Date; endsAt: Date };
export function slotIsBlockedByExceptions(input: { slotStart: Date; slotEnd: Date; exceptions: BlockingException[]; professionalIds: Set<string>; unitIds: Set<string> }) { return input.exceptions.some((item) => item.startsAt < input.slotEnd && item.endsAt > input.slotStart && (item.professionalId === null || input.professionalIds.has(item.professionalId)) && (item.unitId === null || input.unitIds.has(item.unitId))); }
export async function createAvailabilityExceptionBlocker(input: { companyId: string; professionalId?: string; unitId?: string; candidateResourceIds: string[]; searchStart: Date; searchEnd: Date }) {
  const db = getDb(); const professionalCondition = input.professionalId ? eq(professionals.id, input.professionalId) : input.candidateResourceIds.length ? inArray(professionals.resourceId, input.candidateResourceIds) : sql`false`;
  const professionalRows = await db.select({ id: professionals.id, resourceId: professionals.resourceId }).from(professionals).where(and(eq(professionals.companyId, input.companyId), professionalCondition));
  const professionalIds = professionalRows.map((item) => item.id); const primaryUnits = new Map<string, string>();
  if (professionalIds.length) { const links = await db.select({ professionalId: professionalUnits.professionalId, unitId: professionalUnits.unitId, isPrimary: professionalUnits.isPrimary }).from(professionalUnits).where(and(eq(professionalUnits.companyId, input.companyId), inArray(professionalUnits.professionalId, professionalIds), eq(professionalUnits.active, true))).orderBy(desc(professionalUnits.isPrimary)); for (const link of links) if (!primaryUnits.has(link.professionalId)) primaryUnits.set(link.professionalId, link.unitId); }
  const exceptions = await db.select({ professionalId: availabilityExceptions.professionalId, unitId: availabilityExceptions.unitId, startsAt: availabilityExceptions.startsAt, endsAt: availabilityExceptions.endsAt }).from(availabilityExceptions).where(and(eq(availabilityExceptions.companyId, input.companyId), eq(availabilityExceptions.status, "active"), lt(availabilityExceptions.startsAt, input.searchEnd), gt(availabilityExceptions.endsAt, input.searchStart)));
  const professionalByResource = new Map(professionalRows.filter((item) => item.resourceId).map((item) => [item.resourceId!, item.id]));
  return (slotStart: Date, slotEnd: Date, chosenResourceIds: string[]) => { const chosenProfessionals = new Set<string>(); if (input.professionalId) chosenProfessionals.add(input.professionalId); for (const resourceId of chosenResourceIds) { const professionalId = professionalByResource.get(resourceId); if (professionalId) chosenProfessionals.add(professionalId); } const unitIds = new Set<string>(); if (input.unitId) unitIds.add(input.unitId); for (const professionalId of chosenProfessionals) { const unitId = primaryUnits.get(professionalId); if (unitId) unitIds.add(unitId); } return slotIsBlockedByExceptions({ slotStart, slotEnd, exceptions, professionalIds: chosenProfessionals, unitIds }); };
}
