import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireApiRole } from "@/lib/auth/apiAuth";
import { ServiceCatalogSchema } from "@/modules/services/ServiceCatalog.schema";
import { deactivateCompanyService, getCompanyService, updateCompanyService } from "@/modules/services/ServiceCatalog.service";
const Id = z.string().uuid(); const missing = () => NextResponse.json({ ok: false, error: "service_not_found", message: "Serviço não encontrado." }, { status: 404 });
export async function GET(request: NextRequest, context: { params: Promise<{ id: string }> }) { try { const auth = await requireApiRole(request, ["owner", "admin", "staff"]); if (auth.ok === false) return auth.response; const id = Id.safeParse((await context.params).id); if (!id.success) return missing(); const item = await getCompanyService(auth.auth.companyId, id.data); return item ? NextResponse.json({ ok: true, item }) : missing(); } catch { return NextResponse.json({ ok: false, error: "internal_error" }, { status: 500 }); } }
export async function PUT(request: NextRequest, context: { params: Promise<{ id: string }> }) { try { const auth = await requireApiRole(request, ["owner", "admin"]); if (auth.ok === false) return auth.response; const id = Id.safeParse((await context.params).id); if (!id.success) return missing(); const input = ServiceCatalogSchema.safeParse(await request.json()); if (!input.success) return NextResponse.json({ ok: false, error: "invalid_service", issues: input.error.flatten().fieldErrors }, { status: 400 }); const item = await updateCompanyService(auth.auth.companyId, id.data, input.data); return item ? NextResponse.json({ ok: true, item }) : missing(); } catch { return NextResponse.json({ ok: false, error: "internal_error" }, { status: 500 }); } }
export async function DELETE(request: NextRequest, context: { params: Promise<{ id: string }> }) { try { const auth = await requireApiRole(request, ["owner", "admin"]); if (auth.ok === false) return auth.response; const id = Id.safeParse((await context.params).id); if (!id.success) return missing(); const item = await deactivateCompanyService(auth.auth.companyId, id.data); return item ? NextResponse.json({ ok: true, item, deactivated: true }) : missing(); } catch { return NextResponse.json({ ok: false, error: "internal_error" }, { status: 500 }); } }
