import type{AuthorizedAudioDownload}from"./WhatsAppAudioTranscription";

export const META_WHATSAPP_MEDIA_POLICY={version:"meta_whatsapp_media_v1",graphOrigin:"https://graph.facebook.com",graphVersion:"v23.0",allowedDownloadHosts:["lookaside.fbsbx.com","lookaside.facebook.com"],timeoutMs:15_000}as const;
export type MetaMediaDownloadErrorCode="invalid_configuration"|"invalid_media_id"|"metadata_http_error"|"metadata_invalid"|"media_host_not_allowed"|"media_too_large"|"media_http_error"|"media_type_mismatch"|"media_empty"|"network_error";
export class MetaMediaDownloadError extends Error{constructor(readonly code:MetaMediaDownloadErrorCode){super(code);this.name="MetaMediaDownloadError"}}
type FetchLike=(input:string|URL,init?:RequestInit)=>Promise<Response>;

const cleanMime=(value:string)=>value.split(";",1)[0].trim().toLowerCase();
function authorizedMediaUrl(raw:string){let url:URL;try{url=new URL(raw)}catch{throw new MetaMediaDownloadError("metadata_invalid")}if(url.protocol!=="https:"||url.username||url.password||url.port||!(META_WHATSAPP_MEDIA_POLICY.allowedDownloadHosts as readonly string[]).includes(url.hostname.toLowerCase()))throw new MetaMediaDownloadError("media_host_not_allowed");return url}
async function readBounded(response:Response,maximumBytes:number){const declared=Number(response.headers.get("content-length"));if(Number.isFinite(declared)&&declared>maximumBytes)throw new MetaMediaDownloadError("media_too_large");if(!response.body){const bytes=new Uint8Array(await response.arrayBuffer());if(!bytes.byteLength)throw new MetaMediaDownloadError("media_empty");if(bytes.byteLength>maximumBytes)throw new MetaMediaDownloadError("media_too_large");return bytes}const reader=response.body.getReader(),chunks:Uint8Array[]=[],total={value:0};try{while(true){const part=await reader.read();if(part.done)break;total.value+=part.value.byteLength;if(total.value>maximumBytes){await reader.cancel();throw new MetaMediaDownloadError("media_too_large")}chunks.push(part.value)}}finally{reader.releaseLock()}if(!total.value)throw new MetaMediaDownloadError("media_empty");const bytes=new Uint8Array(total.value);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}return bytes}

export class MetaWhatsAppMediaDownloader{private readonly token:string;private readonly fetcher:FetchLike;private readonly graphVersion:string;constructor(options:{accessToken:string;fetch?:FetchLike;graphVersion?:string}){this.token=options.accessToken.trim();this.fetcher=options.fetch??fetch;this.graphVersion=options.graphVersion??META_WHATSAPP_MEDIA_POLICY.graphVersion;if(!this.token||!/^v\d+\.\d+$/.test(this.graphVersion))throw new MetaMediaDownloadError("invalid_configuration")}async downloadByMediaId(mediaId:string,maximumBytes:number):Promise<AuthorizedAudioDownload>{if(!/^[A-Za-z0-9._:-]{1,255}$/.test(mediaId))throw new MetaMediaDownloadError("invalid_media_id");if(!Number.isSafeInteger(maximumBytes)||maximumBytes<1)throw new MetaMediaDownloadError("invalid_configuration");const headers={authorization:"Bearer "+this.token};try{const metadataResponse=await this.fetcher(META_WHATSAPP_MEDIA_POLICY.graphOrigin+"/"+this.graphVersion+"/"+encodeURIComponent(mediaId),{method:"GET",headers,redirect:"error",signal:AbortSignal.timeout(META_WHATSAPP_MEDIA_POLICY.timeoutMs)});if(!metadataResponse.ok)throw new MetaMediaDownloadError("metadata_http_error");const metadata=await metadataResponse.json()as{url?:unknown;mime_type?:unknown;file_size?:unknown;id?:unknown};if(typeof metadata.url!=="string"||typeof metadata.mime_type!=="string"||String(metadata.id??"")!==mediaId)throw new MetaMediaDownloadError("metadata_invalid");const fileSize=Number(metadata.file_size);if(Number.isFinite(fileSize)&&fileSize>maximumBytes)throw new MetaMediaDownloadError("media_too_large");const mimeType=cleanMime(metadata.mime_type),mediaUrl=authorizedMediaUrl(metadata.url),mediaResponse=await this.fetcher(mediaUrl,{method:"GET",headers,redirect:"error",signal:AbortSignal.timeout(META_WHATSAPP_MEDIA_POLICY.timeoutMs)});if(!mediaResponse.ok)throw new MetaMediaDownloadError("media_http_error");const responseMime=cleanMime(mediaResponse.headers.get("content-type")??"");if(responseMime!==mimeType)throw new MetaMediaDownloadError("media_type_mismatch");return{bytes:await readBounded(mediaResponse,maximumBytes),mimeType}}catch(error){if(error instanceof MetaMediaDownloadError)throw error;throw new MetaMediaDownloadError("network_error")}}}
