export const WHATSAPP_AUDIO_POLICY={version:"whatsapp_audio_v1",maximumBytes:10*1024*1024,maximumDurationSeconds:180,timeoutMs:20_000,language:"pt-BR",allowedMimeTypes:["audio/ogg","audio/mpeg","audio/mp4","audio/aac","audio/amr"]}as const;

export type WhatsAppAudioDescriptor={mediaId:string;mimeType:string;durationSeconds?:number;voice?:boolean};
export type AuthorizedAudioDownload={bytes:Uint8Array;mimeType:string};
export type WhatsAppAudioDependencies={downloadByMediaId:(mediaId:string,maximumBytes:number)=>Promise<AuthorizedAudioDownload>;transcribe:(input:{bytes:Uint8Array;mimeType:string;language:string;timeoutMs:number})=>Promise<{text:string;confidence?:number}>};
export type WhatsAppAudioResult={ok:true;text:string;confidence:number|null;policyVersion:string}|{ok:false;error:"invalid_media_id"|"unsupported_audio_type"|"audio_too_long"|"audio_too_large"|"empty_transcription"|"transcription_failed";policyVersion:string};

const cleanMime=(value:string)=>value.split(";",1)[0].trim().toLowerCase();
export async function transcribeAuthorizedWhatsAppAudio(descriptor:WhatsAppAudioDescriptor,deps:WhatsAppAudioDependencies):Promise<WhatsAppAudioResult>{const policy=WHATSAPP_AUDIO_POLICY,fail=(error:WhatsAppAudioResult extends infer _T?"invalid_media_id"|"unsupported_audio_type"|"audio_too_long"|"audio_too_large"|"empty_transcription"|"transcription_failed":never):WhatsAppAudioResult=>({ok:false,error,policyVersion:policy.version});if(!/^[A-Za-z0-9._:-]{1,255}$/.test(descriptor.mediaId))return fail("invalid_media_id");const declaredMime=cleanMime(descriptor.mimeType);if(!policy.allowedMimeTypes.includes(declaredMime as typeof policy.allowedMimeTypes[number]))return fail("unsupported_audio_type");if(descriptor.durationSeconds!==undefined&&(!Number.isFinite(descriptor.durationSeconds)||descriptor.durationSeconds<0||descriptor.durationSeconds>policy.maximumDurationSeconds))return fail("audio_too_long");try{const media=await deps.downloadByMediaId(descriptor.mediaId,policy.maximumBytes);if(media.bytes.byteLength===0)return fail("empty_transcription");if(media.bytes.byteLength>policy.maximumBytes)return fail("audio_too_large");const actualMime=cleanMime(media.mimeType);if(actualMime!==declaredMime||!policy.allowedMimeTypes.includes(actualMime as typeof policy.allowedMimeTypes[number]))return fail("unsupported_audio_type");const result=await deps.transcribe({bytes:media.bytes,mimeType:actualMime,language:policy.language,timeoutMs:policy.timeoutMs}),text=result.text.trim();if(!text)return fail("empty_transcription");return{ok:true,text,confidence:typeof result.confidence==="number"&&Number.isFinite(result.confidence)?Math.min(1,Math.max(0,result.confidence)):null,policyVersion:policy.version}}catch{return fail("transcription_failed")}}
