FROM node:20-alpine

WORKDIR /app

# deps mínimas
RUN npm i --omit=dev pg

# copia o dispatcher real do repo
COPY src/workers/outbox-dispatcher.js /app/outbox-dispatcher.js

CMD ["node", "/app/outbox-dispatcher.js"]
