FROM node:20-alpine

WORKDIR /app

# copia build pronto (dist) + package.json caso use deps
COPY dist/ /app/dist/
COPY package.json /app/package.json

# se precisa node_modules:
# (use pnpm/yarn/npm conforme seu projeto)
# RUN npm ci --omit=dev

CMD ["node", "dist/index.js"]
