import { and, asc, eq, ilike } from "drizzle-orm";
import { services } from "@/drizzle/schema";
import { getDb } from "@/lib/db";
import type { ServiceCatalogInput, ServicePricingMode } from "./ServiceCatalog.schema";
export type ServiceStatusFilter = "active" | "inactive" | "all";
export type ServiceCatalogItem = { id: string; name: string; description: string | null; durationMinutes: number; price: string | null; pricingMode: ServicePricingMode; active: boolean };
type Dependencies = { list?: (companyId: string, search: string, status: ServiceStatusFilter) => Promise<ServiceCatalogItem[]>; find?: (companyId: string, serviceId: string) => Promise<ServiceCatalogItem | null>; create?: (companyId: string, input: ServiceCatalogInput) => Promise<ServiceCatalogItem>; update?: (companyId: string, serviceId: string, input: ServiceCatalogInput) => Promise<ServiceCatalogItem | null>; deactivate?: (companyId: string, serviceId: string) => Promise<ServiceCatalogItem | null> };
const requireCompany = (companyId: string) => { if (!companyId.trim()) throw new Error("missing_company_id"); };
const present = (row: typeof services.$inferSelect): ServiceCatalogItem => ({ id: row.id, name: row.name, description: row.description, durationMinutes: row.durationMinutes, price: row.price, pricingMode: row.price === null ? "on_request" : Number(row.price) === 0 ? "free" : "fixed", active: row.active });
async function listDb(companyId: string, search: string, status: ServiceStatusFilter) { const filters = [eq(services.companyId, companyId)]; if (search) filters.push(ilike(services.name, "%" + search + "%")); if (status === "active") filters.push(eq(services.active, true)); if (status === "inactive") filters.push(eq(services.active, false)); const rows = await getDb().select().from(services).where(and(...filters)).orderBy(asc(services.name)); return rows.map(present); }
async function findDb(companyId: string, serviceId: string) { const rows = await getDb().select().from(services).where(and(eq(services.companyId, companyId), eq(services.id, serviceId))).limit(1); return rows[0] ? present(rows[0]) : null; }
async function createDb(companyId: string, input: ServiceCatalogInput) { const rows = await getDb().insert(services).values({ companyId, name: input.name, description: input.description, durationMinutes: input.durationMinutes, price: input.price, active: input.active }).returning(); return present(rows[0]!); }
async function updateDb(companyId: string, serviceId: string, input: ServiceCatalogInput) { const rows = await getDb().update(services).set({ name: input.name, description: input.description, durationMinutes: input.durationMinutes, price: input.price, active: input.active, updatedAt: new Date() }).where(and(eq(services.companyId, companyId), eq(services.id, serviceId))).returning(); return rows[0] ? present(rows[0]) : null; }
async function deactivateDb(companyId: string, serviceId: string) { const rows = await getDb().update(services).set({ active: false, updatedAt: new Date() }).where(and(eq(services.companyId, companyId), eq(services.id, serviceId))).returning(); return rows[0] ? present(rows[0]) : null; }
export async function listCompanyServices(companyId: string, search = "", status: ServiceStatusFilter = "active", dependencies: Dependencies = {}) { requireCompany(companyId); return (dependencies.list ?? listDb)(companyId, search.trim(), status); }
export async function getCompanyService(companyId: string, serviceId: string, dependencies: Dependencies = {}) { requireCompany(companyId); return (dependencies.find ?? findDb)(companyId, serviceId); }
export async function createCompanyService(companyId: string, input: ServiceCatalogInput, dependencies: Dependencies = {}) { requireCompany(companyId); return (dependencies.create ?? createDb)(companyId, input); }
export async function updateCompanyService(companyId: string, serviceId: string, input: ServiceCatalogInput, dependencies: Dependencies = {}) { requireCompany(companyId); return (dependencies.update ?? updateDb)(companyId, serviceId, input); }
export async function deactivateCompanyService(companyId: string, serviceId: string, dependencies: Dependencies = {}) { requireCompany(companyId); return (dependencies.deactivate ?? deactivateDb)(companyId, serviceId); }
