import { NextRequest, NextResponse } from "next/server";
import { requireApiRole } from "@/lib/auth/apiAuth";
import { RecoveryRetrievalReleaseRollbackProposalSchema } from "@/modules/agents/RecoveryRetrievalReleaseRollbackProposal.schema";
import { RecoveryRetrievalReleaseRollbackProposalService } from "@/modules/agents/RecoveryRetrievalReleaseRollbackProposal.service";
import { RecoveryRetrievalReleaseRollbackReviewSchema } from "@/modules/agents/RecoveryRetrievalReleaseRollbackReview.schema";
import { RecoveryRetrievalReleaseRollbackReviewService } from "@/modules/agents/RecoveryRetrievalReleaseRollbackReview.service";
import { RecoveryRetrievalReleaseRollbackApplySchema } from "@/modules/agents/RecoveryRetrievalReleaseRollbackApply.schema";
import { RecoveryRetrievalReleaseRollbackApplyService } from "@/modules/agents/RecoveryRetrievalReleaseRollbackApply.service";
export async function GET(request: NextRequest) { const auth = await requireApiRole(request, ["owner"]); if (auth.ok === false) return auth.response; return NextResponse.json(await RecoveryRetrievalReleaseRollbackProposalService.list({ companyId: auth.auth.companyId })); }
export async function POST(request: NextRequest) { const auth = await requireApiRole(request, ["owner"]); if (auth.ok === false) return auth.response; const parsed = RecoveryRetrievalReleaseRollbackProposalSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ ok: false, error: "invalid_payload" }, { status: 400 }); const result = await RecoveryRetrievalReleaseRollbackProposalService.create({ companyId: auth.auth.companyId, actorId: auth.auth.userId, proposal: parsed.data }); if (result.ok) return NextResponse.json(result, { status: 201 }); return NextResponse.json(result, { status: result.error === "scheduled_release_plan_not_found" ? 404 : 409 }); }
export async function PATCH(request: NextRequest) { const auth = await requireApiRole(request, ["owner"]); if (auth.ok === false) return auth.response; const parsed = RecoveryRetrievalReleaseRollbackReviewSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ ok: false, error: "invalid_payload" }, { status: 400 }); const result = await RecoveryRetrievalReleaseRollbackReviewService.review({ companyId: auth.auth.companyId, actorId: auth.auth.userId, review: parsed.data }); return NextResponse.json(result, { status: result.ok ? 200 : 409 }); }

export async function PUT(request: NextRequest) { const auth = await requireApiRole(request, ["owner"]); if (auth.ok === false) return auth.response; const parsed = RecoveryRetrievalReleaseRollbackApplySchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ ok: false, error: "invalid_payload" }, { status: 400 }); const result = await RecoveryRetrievalReleaseRollbackApplyService.apply({ companyId: auth.auth.companyId, actorId: auth.auth.userId, command: parsed.data }); return NextResponse.json(result, { status: result.ok ? 200 : 409 }); }
