import { and, asc, eq } from "drizzle-orm";
import { professionalServices, professionals, services } from "@/drizzle/schema"; import { getDb } from "@/lib/db"; import type { ProfessionalServiceInput } from "./ProfessionalService.schema";
export class ProfessionalServiceError extends Error { constructor(public code: "professional_not_found" | "service_not_found" | "link_not_found") { super(code); } }
export type ProfessionalServiceItem = { id: string; serviceId: string; serviceName: string; catalogDurationMinutes: number; catalogPrice: string | null; durationOverrideMinutes: number | null; priceOverride: string | null; effectiveDurationMinutes: number; effectivePrice: string | null; active: boolean };
type Dependencies = { list?: (companyId: string, professionalId: string) => Promise<ProfessionalServiceItem[]>; link?: (companyId: string, professionalId: string, input: ProfessionalServiceInput) => Promise<ProfessionalServiceItem>; deactivate?: (companyId: string, professionalId: string, serviceId: string) => Promise<unknown> };
const boundary = (companyId: string, professionalId: string) => { if (!companyId.trim()) throw new Error("missing_company_id"); if (!professionalId.trim()) throw new Error("missing_professional_id"); };
const select = { id: professionalServices.id, serviceId: professionalServices.serviceId, serviceName: services.name, catalogDurationMinutes: services.durationMinutes, catalogPrice: services.price, durationOverrideMinutes: professionalServices.durationOverrideMinutes, priceOverride: professionalServices.priceOverride, active: professionalServices.active };
const present = (row: Omit<ProfessionalServiceItem, "effectiveDurationMinutes" | "effectivePrice">): ProfessionalServiceItem => ({ ...row, effectiveDurationMinutes: row.durationOverrideMinutes ?? row.catalogDurationMinutes, effectivePrice: row.priceOverride ?? row.catalogPrice });
async function listDb(companyId: string, professionalId: string) { const rows = await getDb().select(select).from(professionalServices).innerJoin(services, and(eq(services.companyId, companyId), eq(services.id, professionalServices.serviceId))).where(and(eq(professionalServices.companyId, companyId), eq(professionalServices.professionalId, professionalId))).orderBy(asc(services.name)); return rows.map(present); }
async function linkDb(companyId: string, professionalId: string, input: ProfessionalServiceInput) { return getDb().transaction(async (tx) => { const professional = await tx.select({ id: professionals.id }).from(professionals).where(and(eq(professionals.companyId, companyId), eq(professionals.id, professionalId))).limit(1); if (!professional[0]) throw new ProfessionalServiceError("professional_not_found"); const service = await tx.select({ id: services.id, name: services.name, durationMinutes: services.durationMinutes, price: services.price }).from(services).where(and(eq(services.companyId, companyId), eq(services.id, input.serviceId), eq(services.active, true))).limit(1); if (!service[0]) throw new ProfessionalServiceError("service_not_found"); const existing = await tx.select({ id: professionalServices.id }).from(professionalServices).where(and(eq(professionalServices.companyId, companyId), eq(professionalServices.professionalId, professionalId), eq(professionalServices.serviceId, input.serviceId))).limit(1); const values = { durationOverrideMinutes: input.durationOverrideMinutes, priceOverride: input.priceOverride, active: true, updatedAt: new Date() }; const rows = existing[0] ? await tx.update(professionalServices).set(values).where(eq(professionalServices.id, existing[0].id)).returning() : await tx.insert(professionalServices).values({ companyId, professionalId, serviceId: input.serviceId, ...values }).returning(); const row = rows[0]!; return present({ id: row.id, serviceId: row.serviceId, serviceName: service[0].name, catalogDurationMinutes: service[0].durationMinutes, catalogPrice: service[0].price, durationOverrideMinutes: row.durationOverrideMinutes, priceOverride: row.priceOverride, active: row.active }); }); }
async function deactivateDb(companyId: string, professionalId: string, serviceId: string) { const rows = await getDb().update(professionalServices).set({ active: false, updatedAt: new Date() }).where(and(eq(professionalServices.companyId, companyId), eq(professionalServices.professionalId, professionalId), eq(professionalServices.serviceId, serviceId), eq(professionalServices.active, true))).returning({ id: professionalServices.id }); if (!rows[0]) throw new ProfessionalServiceError("link_not_found"); return rows[0]; }
export async function listProfessionalServices(companyId: string, professionalId: string, dependencies: Dependencies = {}) { boundary(companyId, professionalId); return (dependencies.list ?? listDb)(companyId, professionalId); }
export async function linkProfessionalService(companyId: string, professionalId: string, input: ProfessionalServiceInput, dependencies: Dependencies = {}) { boundary(companyId, professionalId); return (dependencies.link ?? linkDb)(companyId, professionalId, input); }
export async function deactivateProfessionalService(companyId: string, professionalId: string, serviceId: string, dependencies: Dependencies = {}) { boundary(companyId, professionalId); return (dependencies.deactivate ?? deactivateDb)(companyId, professionalId, serviceId); }
