import { and, eq, inArray } from "drizzle-orm";
import { bookingEvents, bookingRecoveryRecommendations, recoveryAgentKnowledgeDocuments, recoveryAgentRetrievalEvaluations } from "@/drizzle/schema";
import { getDb } from "@/lib/db";
import type { RecoveryRetrievalEvaluation } from "./RecoveryRetrievalEvaluation.schema";
const record=(v:unknown):Record<string,unknown>=>v!==null&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};
const ids=(v:unknown)=>Array.isArray(v)?v.filter((x):x is string=>typeof x==="string").slice(0,3):[];
export class RecoveryRetrievalEvaluationService{
static async context(input:{companyId:string;caseId:string}){const db=getDb(),rows=await db.select({id:bookingRecoveryRecommendations.id,bookingId:bookingRecoveryRecommendations.bookingId,clientId:bookingRecoveryRecommendations.clientId,version:bookingRecoveryRecommendations.version,execution:bookingRecoveryRecommendations.agentExecution}).from(bookingRecoveryRecommendations).where(and(eq(bookingRecoveryRecommendations.companyId,input.companyId),eq(bookingRecoveryRecommendations.recoveryCaseId,input.caseId))).limit(1),current=rows[0];if(!current)return{ok:false as const,error:"recommendation_not_found"as const};const retrieval=record(record(current.execution).retrievalShadow),lexical=ids(retrieval.lexicalTopDocumentIds),vector=ids(retrieval.topDocumentIds),all=[...new Set([...lexical,...vector])];const documents=all.length?await db.select({id:recoveryAgentKnowledgeDocuments.id,title:recoveryAgentKnowledgeDocuments.title,version:recoveryAgentKnowledgeDocuments.version,contentHash:recoveryAgentKnowledgeDocuments.contentHash}).from(recoveryAgentKnowledgeDocuments).where(and(eq(recoveryAgentKnowledgeDocuments.companyId,input.companyId),inArray(recoveryAgentKnowledgeDocuments.id,all))):[];const evaluations=all.length?await db.select().from(recoveryAgentRetrievalEvaluations).where(and(eq(recoveryAgentRetrievalEvaluations.companyId,input.companyId),eq(recoveryAgentRetrievalEvaluations.recommendationId,current.id),eq(recoveryAgentRetrievalEvaluations.recommendationVersion,current.version))):[];return{ok:true as const,...current,recommendationId:current.id,recommendationVersion:current.version,rankings:{lexical,vector},documents,evaluations}}
static async evaluate(input:{companyId:string;caseId:string;actorId:string;command:RecoveryRetrievalEvaluation}){const db=getDb(),context=await this.context(input);if(!context.ok)return context;if(context.recommendationVersion!==input.command.recommendationVersion)return{ok:false as const,error:"stale_recommendation"as const};const rank=context.rankings[input.command.strategy].indexOf(input.command.documentId)+1;if(!rank)return{ok:false as const,error:"document_not_in_ranking"as const};const now=new Date(),saved=await db.insert(recoveryAgentRetrievalEvaluations).values({companyId:input.companyId,recommendationId:context.recommendationId,recommendationVersion:context.recommendationVersion,documentId:input.command.documentId,strategy:input.command.strategy,rank,relevance:input.command.relevance,note:input.command.note??null,evaluatedBy:input.actorId,updatedAt:now}).onConflictDoUpdate({target:[recoveryAgentRetrievalEvaluations.companyId,recoveryAgentRetrievalEvaluations.recommendationId,recoveryAgentRetrievalEvaluations.recommendationVersion,recoveryAgentRetrievalEvaluations.strategy,recoveryAgentRetrievalEvaluations.documentId],set:{relevance:input.command.relevance,note:input.command.note??null,evaluatedBy:input.actorId,rank,updatedAt:now}}).returning({id:recoveryAgentRetrievalEvaluations.id});await db.insert(bookingEvents).values({companyId:input.companyId,bookingId:context.bookingId,clientId:context.clientId,type:"automation.booking_recovery.retrieval_evaluated",actor:"admin",payload:{caseId:input.caseId,recommendationId:context.recommendationId,recommendationVersion:context.recommendationVersion,documentId:input.command.documentId,strategy:input.command.strategy,rank,relevance:input.command.relevance,actorId:input.actorId,evaluatedAt:now.toISOString()}});return{ok:true as const,id:saved[0]!.id,rank}}
}
