import type { RecoveryKnowledgeDocument, RecoveryKnowledgeExcerpt } from "./RecoverySemanticRetriever";

export const RECOVERY_VECTOR_MAX_CANDIDATES = 20;
export const RECOVERY_VECTOR_MAX_INPUT_CHARS = 1000;
export type EmbeddingResponse = { vectors: number[][]; model: string; totalTokens?: number };
export interface RecoveryEmbeddingProvider { embed(inputs: string[], timeoutMs: number): Promise<EmbeddingResponse> }

const cosine = (a: number[], b: number[]) => { if (!a.length || a.length !== b.length) return 0; let dot=0,aa=0,bb=0; for(let i=0;i<a.length;i++){dot+=a[i]!*b[i]!;aa+=a[i]!*a[i]!;bb+=b[i]!*b[i]!} return aa&&bb?dot/(Math.sqrt(aa)*Math.sqrt(bb)):0 };
export async function executeVectorRetrievalShadow(input:{companyId:string;queryTerms:string[];candidates:RecoveryKnowledgeDocument[];lexical:RecoveryKnowledgeExcerpt[];provider?:RecoveryEmbeddingProvider;providerName?:string;timeoutMs?:number;now?:Date}){
  const started=Date.now(),provider=input.providerName??null;if(!input.provider)return{mode:"fallback"as const,provider,model:null,totalTokens:0,durationMs:0,errorCode:"embedding_provider_not_configured",topDocumentIds:[],lexicalTopDocumentIds:input.lexical.map(x=>x.documentId),overlapRate:0};
  const now=input.now??new Date(),candidates=input.candidates.filter(x=>x.companyId===input.companyId&&x.status==="approved"&&x.validFrom<=now&&(!x.validUntil||x.validUntil>now)&&x.content.trim().length>0&&x.content.length<=2000).sort((a,b)=>a.id.localeCompare(b.id)).slice(0,RECOVERY_VECTOR_MAX_CANDIDATES),query=input.queryTerms.join(" ").slice(0,RECOVERY_VECTOR_MAX_INPUT_CHARS),texts=[query,...candidates.map(x=>(x.title+"\n"+x.content).slice(0,RECOVERY_VECTOR_MAX_INPUT_CHARS))];
  try{const timeout=Math.min(Math.max(Number.isFinite(input.timeoutMs)?input.timeoutMs!:8000,1000),20000),result=await input.provider.embed(texts,timeout);if(result.vectors.length!==texts.length)throw new Error("invalid_embedding_count");const q=result.vectors[0]!,ranked=candidates.map((document,index)=>({documentId:document.id,score:cosine(q,result.vectors[index+1]!)})).sort((a,b)=>b.score-a.score||a.documentId.localeCompare(b.documentId)).slice(0,3),top=ranked.map(x=>x.documentId),lexical=input.lexical.map(x=>x.documentId),overlap=top.filter(id=>lexical.includes(id)).length;return{mode:"ai"as const,provider,model:result.model,totalTokens:Math.max(0,result.totalTokens??0),durationMs:Date.now()-started,errorCode:null,topDocumentIds:top,lexicalTopDocumentIds:lexical,overlapRate:lexical.length?Number((overlap*100/lexical.length).toFixed(1)):0}}catch{return{mode:"fallback"as const,provider,model:null,totalTokens:0,durationMs:Date.now()-started,errorCode:"embedding_provider_error",topDocumentIds:[],lexicalTopDocumentIds:input.lexical.map(x=>x.documentId),overlapRate:0}}
}
