import fs from "node:fs";import { describe,expect,it } from "vitest";
const load=(file:string)=>fs.readFileSync(file,"utf8");
describe("retrieval release graduation operational readiness",()=>{
 const gate=load("src/modules/agents/RecoveryRetrievalReleaseGraduationGate.ts"),proposal=load("src/modules/agents/RecoveryRetrievalReleaseGraduationProposal.service.ts"),review=load("src/modules/agents/RecoveryRetrievalReleaseGraduationReview.service.ts"),apply=load("src/modules/agents/RecoveryRetrievalReleaseGraduationApply.service.ts"),runtime=load("src/modules/agents/RecoveryRetrievalReleasePlanRuntime.service.ts"),route=load("src/app/api/v1/settings/booking-followups/recovery/agent-outcomes/release-graduation-proposals/route.ts"),schema=load("src/drizzle/schema.ts"),migration=load("infra/recovery-agent-retrieval-release-graduation-apply.sql"),page=load("src/app/admin/settings/booking-followups/recovery/agent-outcomes/release-graduation-proposals/page.tsx");
 it("keeps every mutable boundary tenant and owner scoped",()=>{for(const service of [proposal,review,apply])expect(service).toContain("input.companyId");expect(route.split('requireApiRole(request,["owner"])').length-1).toBeGreaterThanOrEqual(4);expect(route.match(/auth.auth.companyId/g)?.length).toBeGreaterThanOrEqual(4);expect(route).toContain("auth.auth.userId")});
 it("requires full healthy release before proposal and application",()=>{for(const value of ["requiredRolloutPercent: 100",'plan.health.status !== "healthy"',"release_window_not_active","automaticGraduation: false"])expect(gate).toContain(value);expect(proposal).toContain('decision.status !== "eligible_for_graduation"');expect(apply).toContain('decision.status!=="eligible_for_graduation"')});
 it("freezes and revalidates policy versions",()=>{for(const value of ["healthPolicyVersion","graduationPolicyVersion","observedFrom","observedTo"])expect(proposal).toContain(value);expect(apply).toContain("release_graduation_policy_changed");expect(apply).toContain("applicationEvidence:")});
 it("protects review and apply with optimistic versions",()=>{for(const service of [review,apply]){expect(service).toContain("version");expect(service).toContain("expectedVersion")};expect(review).toContain('status,"proposed"');expect(apply).toContain('status,"approved"')});
 it("updates graduation atomically and fails closed on conflicts",()=>{expect(apply).toContain("db.transaction(async tx");for(const value of ["release_plan_changed","concurrent_release_graduation",'status:"graduated"','status:"applied"'])expect(apply).toContain(value)});
 it("allows one live release and resolves graduated state as stable",()=>{expect(schema).toContain("recovery_retrieval_release_plans_live_uq");expect(schema).toContain("('scheduled','graduated')");expect(migration).toContain("WHERE status IN ('scheduled','graduated')");expect(runtime).toContain('eq(recoveryAgentRetrievalReleasePlans.status,"graduated")');expect(runtime).toContain('stableRelease:row.status==="graduated"')});
 it("keeps external integrations outside the graduation path",()=>{for(const source of [proposal,review,apply])for(const forbidden of ["outbox","WhatsApp","MCP","sendMessage","provider.send"])expect(source).not.toContain(forbidden)});
 it("requires explicit human actions in the UI",()=>{for(const value of ["window.confirm","window.prompt",'method: "PATCH"','method: "PUT"',"nenhuma graduação ocorre automaticamente"])expect(page).toContain(value)});
});
