"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { HeartHandshake, Save, Star } from "lucide-react";
import { ActionFeedback } from "@/components/ui/ActionFeedback"; import { Button } from "@/components/ui/button"; import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { SisagDataState, SisagPage, SisagPageHeader } from "@/components/sisag"; import { DEFAULT_BOOKING_FOLLOWUP_TEMPLATE, type BookingFollowupSettings } from "@/modules/automation/BookingFollowupSettings.schema";
type Insights = { summary: { total: number; average: number; distribution: Array<{ score: number; count: number }> }; recovery: Array<{ id: string; bookingId: string; score: number; clientName: string; createdAt: string; bookingStartTime: string }> };
const defaults: BookingFollowupSettings = { enabled: false, hoursAfter: 24, template: DEFAULT_BOOKING_FOLLOWUP_TEMPLATE }; const format = (value: string) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));
export default function BookingFollowupsPage() { const [form, setForm] = useState(defaults); const [insights, setInsights] = useState<Insights | null>(null); const [days, setDays] = useState(30); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [feedback, setFeedback] = useState<{ type: "success" | "error"; message: string } | null>(null); const preview = useMemo(() => form.template.replaceAll("{{nome}}", "Ana"), [form.template]);
  const loadInsights = useCallback(async () => { const response = await fetch("/api/v1/settings/booking-followups/insights?days=" + days, { cache: "no-store" }); const body = await response.json(); if (response.ok) setInsights(body); }, [days]);
  useEffect(() => { void Promise.all([fetch("/api/v1/settings/booking-followups", { cache: "no-store" }).then((r) => r.json()).then((body) => { if (body.settings) setForm(body.settings); }), loadInsights()]).catch(() => setFeedback({ type: "error", message: "Não foi possível carregar o pós-atendimento." })).finally(() => setLoading(false)); }, [loadInsights]);
  async function save() { setSaving(true); setFeedback(null); try { const response = await fetch("/api/v1/settings/booking-followups", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(); setForm(body.settings); setFeedback({ type: "success", message: "Pós-atendimento atualizado." }); } catch { setFeedback({ type: "error", message: "Não foi possível salvar a configuração." }); } finally { setSaving(false); } }
  if (loading) return <SisagPage><SisagDataState state="loading" title="Carregando pós-atendimento" /></SisagPage>;
  return <SisagPage><SisagPageHeader context={<span className="inline-flex items-center gap-2"><HeartHandshake className="h-4 w-4" />Relacionamento</span>} title="Pós-atendimento" description="Agradeça, ouça o cliente e identifique experiências que precisam de cuidado." />{feedback ? <ActionFeedback type={feedback.type} message={feedback.message} /> : null}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="space-y-5"><Card className={form.enabled ? "rounded-2xl border-emerald-200 bg-emerald-50/40" : "rounded-2xl border-slate-200"}><CardContent className="p-5"><label className="flex items-start gap-3"><input type="checkbox" className="mt-1 h-4 w-4" checked={form.enabled} onChange={(event) => setForm((current) => ({ ...current, enabled: event.target.checked }))} /><span><strong className="block text-sm">Enviar mensagem após atendimento concluído</strong><span className="mt-1 block text-sm text-slate-600">O cliente poderá responder com uma nota de 1 a 5.</span></span></label></CardContent></Card><Card className="rounded-2xl border-slate-200"><CardHeader><CardTitle className="text-lg">Momento e mensagem</CardTitle><CardDescription>Envie imediatamente ou até 30 dias após a conclusão.</CardDescription></CardHeader><CardContent className="space-y-5"><div><Label htmlFor="hoursAfter">Horas após o atendimento</Label><Input id="hoursAfter" className="mt-1 max-w-xs" type="number" min={0} max={720} value={form.hoursAfter} onChange={(event) => setForm((current) => ({ ...current, hoursAfter: Number(event.target.value) }))} /></div><div><Label htmlFor="template">Mensagem</Label><textarea id="template" rows={6} maxLength={600} className="mt-1 w-full rounded-md border border-input px-3 py-2 text-sm" value={form.template} onChange={(event) => setForm((current) => ({ ...current, template: event.target.value }))} /><div className="mt-2 flex justify-between text-xs text-slate-500"><button type="button" className="underline" onClick={() => setForm((current) => ({ ...current, template: DEFAULT_BOOKING_FOLLOWUP_TEMPLATE }))}>Restaurar padrão</button><span>{form.template.length}/600</span></div></div></CardContent></Card></div><Card className="h-fit rounded-2xl border-slate-200 xl:sticky xl:top-6"><CardHeader><CardTitle className="text-lg">Prévia</CardTitle></CardHeader><CardContent><div className="rounded-2xl rounded-tr-sm bg-emerald-100 p-4 text-sm leading-6">{preview}</div><p className="mt-4 text-xs text-slate-500">{form.enabled ? "Envio após " + form.hoursAfter + " hora(s)." : "Envio desativado."}</p><Button className="mt-5 w-full" disabled={saving || form.template.trim().length < 20} onClick={() => void save()}><Save className="mr-2 h-4 w-4" />{saving ? "Salvando..." : "Salvar pós-atendimento"}</Button></CardContent></Card></div>
    <div className="flex justify-end"><Button asChild variant="outline"><Link href="/admin/settings/booking-followups/recovery"><HeartHandshake className="mr-2 h-4 w-4" />Abrir fila de recuperação</Link></Button></div><Card className="rounded-2xl border-slate-200"><CardHeader className="gap-4 md:flex-row md:items-start md:justify-between"><div><CardTitle className="text-lg">Satisfação</CardTitle><CardDescription>Avaliações recebidas e clientes que merecem atenção.</CardDescription></div><div className="flex gap-2">{[7,30,90].map((value) => <Button key={value} size="sm" variant={days === value ? "default" : "outline"} onClick={() => setDays(value)}>{value} dias</Button>)}</div></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Média" value={insights?.summary.average ? insights.summary.average.toFixed(1) : "—"} /><Metric label="Respostas" value={String(insights?.summary.total ?? 0)} /><Metric label="Notas 4 e 5" value={String((insights?.summary.distribution[3]?.count ?? 0) + (insights?.summary.distribution[4]?.count ?? 0))} /><Metric label="Precisam atenção" value={String(insights?.recovery.length ?? 0)} /></div><div className="grid gap-2 sm:grid-cols-5">{insights?.summary.distribution.map((item) => <div key={item.score} className="rounded-xl bg-slate-50 p-3 text-center"><div className="flex justify-center gap-1 text-amber-500"><Star className="h-4 w-4 fill-current" /><span className="text-sm font-medium text-slate-700">{item.score}</span></div><p className="mt-1 text-xl font-semibold">{item.count}</p></div>)}</div>{insights?.recovery.length ? <div><h3 className="mb-3 text-sm font-semibold">Recuperação recomendada</h3><div className="space-y-2">{insights.recovery.map((item) => <div key={item.id} className="flex flex-col justify-between gap-2 rounded-xl border border-rose-200 bg-rose-50 p-4 sm:flex-row sm:items-center"><div><p className="font-medium text-slate-900">{item.clientName}</p><p className="text-xs text-slate-600">Atendimento em {format(item.bookingStartTime)}</p></div><span className="rounded-full bg-white px-3 py-1 text-sm font-semibold text-rose-700">Nota {item.score}</span></div>)}</div></div> : <p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Nenhuma avaliação baixa neste período.</p>}</CardContent></Card>
  </SisagPage>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 p-4"><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-slate-500">{label}</p></div>; }
