"use client";
import { useEffect, useMemo, useState } from "react";
import { CalendarCog, Save, ShieldCheck, Sparkles } from "lucide-react";
import { ActionFeedback } from "@/components/ui/ActionFeedback";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SisagDataState, SisagPage, SisagPageHeader } from "@/components/sisag";
import { describeSchedulingPolicy, formatMinutes, SUPPORTED_SCHEDULING_TIMEZONES } from "@/modules/scheduling-config/scheduling-config.presentation";
import type { SchedulingConfigInput } from "@/modules/scheduling-config/scheduling-config.schema";
import { getSchedulingConfig, saveSchedulingConfig } from "@/services/scheduling-config.service";

const defaults: SchedulingConfigInput = { timezone: "America/Sao_Paulo", slotDurationMinutes: 15, bufferMinutes: 5, allowOverbooking: false, maxAdvanceDays: 30, minCancelAdvanceMinutes: 0, defaultUnitId: null, defaultServiceId: null, defaultProfessionalId: null };
type Option = { id: string; name: string | null };
type Unit = Option & { active: boolean; isDefault: boolean };
type Feedback = { type: "success" | "error" | "info"; message: string };
const defaultError: Record<string, string> = { invalid_default_unit: "O local padrão não está ativo.", invalid_default_service: "O serviço padrão não está ativo.", invalid_default_professional: "O profissional padrão não está ativo.", default_professional_not_available_at_unit: "O profissional não atende no local padrão.", default_professional_does_not_perform_service: "O profissional não realiza o serviço padrão." };

export default function SchedulingConfigPage() {
  const [form, setForm] = useState<SchedulingConfigInput>(defaults); const [units, setUnits] = useState<Unit[]>([]); const [services, setServices] = useState<Option[]>([]); const [professionals, setProfessionals] = useState<Option[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [feedback, setFeedback] = useState<Feedback | null>(null); const summary = useMemo(() => describeSchedulingPolicy(form), [form]);
  useEffect(() => { void (async () => { try { const [data, unitsRes, servicesRes] = await Promise.all([getSchedulingConfig(), fetch("/api/v1/me/company/units", { cache: "no-store" }), fetch("/api/v1/services", { cache: "no-store" })]); const unitsJson = await unitsRes.json(); const servicesJson = await servicesRes.json(); setForm(data ? { ...defaults, ...data } : defaults); setUnits((Array.isArray(unitsJson?.items) ? unitsJson.items : []).filter((item: Unit) => item.active)); setServices(Array.isArray(servicesJson?.items) ? servicesJson.items : []); } catch { setFeedback({ type: "error", message: "Não foi possível carregar as regras da agenda." }); } finally { setLoading(false); } })(); }, []);
  useEffect(() => { let active = true; const query = form.defaultUnitId ? "?unitId=" + encodeURIComponent(form.defaultUnitId) : ""; fetch("/api/v1/professionals" + query, { cache: "no-store" }).then((response) => response.json()).then((body) => { if (active) setProfessionals(Array.isArray(body?.items) ? body.items : []); }).catch(() => { if (active) setProfessionals([]); }); return () => { active = false; }; }, [form.defaultUnitId]);
  function number(name: "slotDurationMinutes" | "bufferMinutes" | "maxAdvanceDays" | "minCancelAdvanceMinutes", value: string) { setForm((current) => ({ ...current, [name]: Number(value) })); }
  async function save() { setSaving(true); setFeedback(null); try { const saved = await saveSchedulingConfig(form); setForm({ ...defaults, ...saved }); setFeedback({ type: "success", message: "Regras e padrões atualizados. O próximo agendamento já virá preenchido." }); } catch (error) { const code = error instanceof Error ? error.message : ""; setFeedback({ type: "error", message: defaultError[code] ?? "Não foi possível salvar. Revise os padrões e limites informados." }); } finally { setSaving(false); } }
  if (loading) return <SisagPage><SisagDataState state="loading" title="Carregando regras da agenda" /></SisagPage>;
  return <SisagPage><SisagPageHeader context={<span className="inline-flex items-center gap-2"><CalendarCog className="h-4 w-4" />Configuração operacional</span>} title="Regras da agenda" description="Defina o comportamento da agenda e deixe as escolhas mais frequentes prontas para a equipe." />
    {feedback ? <ActionFeedback type={feedback.type} message={feedback.message} /> : null}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-5">
      <Card className="rounded-2xl border-sky-200 bg-gradient-to-br from-white to-sky-50 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Sparkles className="h-5 w-5 text-sky-600" />Padrões de agendamento</CardTitle><CardDescription>Antecipe as escolhas mais usadas. A equipe poderá alterá-las em cada atendimento.</CardDescription></CardHeader><CardContent className="grid gap-5 md:grid-cols-3"><div><Label htmlFor="defaultUnitId">Local padrão</Label><select id="defaultUnitId" value={form.defaultUnitId ?? ""} onChange={(event) => setForm((current) => ({ ...current, defaultUnitId: event.target.value || null, defaultProfessionalId: null }))} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Sem padrão</option>{units.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><Label htmlFor="defaultServiceId">Serviço padrão</Label><select id="defaultServiceId" value={form.defaultServiceId ?? ""} onChange={(event) => setForm((current) => ({ ...current, defaultServiceId: event.target.value || null }))} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Sem padrão</option>{services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><Label htmlFor="defaultProfessionalId">Profissional padrão</Label><select id="defaultProfessionalId" value={form.defaultProfessionalId ?? ""} onChange={(event) => setForm((current) => ({ ...current, defaultProfessionalId: event.target.value || null }))} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Sem padrão</option>{professionals.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><p className="mt-1 text-xs text-slate-500">A lista respeita o local escolhido.</p></div></CardContent></Card>
      <Card className="rounded-2xl border-slate-200 shadow-sm"><CardHeader><CardTitle className="text-lg">Horários e capacidade</CardTitle><CardDescription>Defina o ritmo padrão. A duração específica do serviço continua tendo prioridade.</CardDescription></CardHeader><CardContent className="grid gap-5 md:grid-cols-2"><div><Label htmlFor="slotDurationMinutes">Duração padrão do atendimento</Label><Input className="mt-1" id="slotDurationMinutes" type="number" min={5} max={480} value={form.slotDurationMinutes} onChange={(event) => number("slotDurationMinutes", event.target.value)} /></div><div><Label htmlFor="bufferMinutes">Intervalo entre atendimentos</Label><Input className="mt-1" id="bufferMinutes" type="number" min={0} max={240} value={form.bufferMinutes} onChange={(event) => number("bufferMinutes", event.target.value)} /></div><div className="md:col-span-2"><Label htmlFor="timezone">Fuso horário</Label><select id="timezone" value={form.timezone} onChange={(event) => setForm((current) => ({ ...current, timezone: event.target.value }))} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{SUPPORTED_SCHEDULING_TIMEZONES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div></CardContent></Card>
      <Card className="rounded-2xl border-slate-200 shadow-sm"><CardHeader><CardTitle className="text-lg">Antecedência e cancelamento</CardTitle></CardHeader><CardContent className="grid gap-5 md:grid-cols-2"><div><Label htmlFor="maxAdvanceDays">Agenda aberta pelos próximos</Label><Input className="mt-1" id="maxAdvanceDays" type="number" min={1} max={730} value={form.maxAdvanceDays} onChange={(event) => number("maxAdvanceDays", event.target.value)} /></div><div><Label htmlFor="minCancelAdvanceMinutes">Antecedência mínima para cancelar</Label><Input className="mt-1" id="minCancelAdvanceMinutes" type="number" min={0} max={43200} value={form.minCancelAdvanceMinutes} onChange={(event) => number("minCancelAdvanceMinutes", event.target.value)} /><p className="mt-1 text-xs text-slate-500">{formatMinutes(form.minCancelAdvanceMinutes)}</p></div></CardContent></Card>
      <Card className={form.allowOverbooking ? "rounded-2xl border-amber-300 bg-amber-50" : "rounded-2xl border-slate-200"}><CardContent className="p-5"><label className="flex items-start gap-3"><input type="checkbox" className="mt-1 h-4 w-4" checked={form.allowOverbooking} onChange={(event) => setForm((current) => ({ ...current, allowOverbooking: event.target.checked }))} /><span><strong className="block text-sm text-slate-900">Permitir encaixes no mesmo horário</strong><span className="mt-1 block text-sm text-slate-600">Desativado, o sistema bloqueia conflitos de horário.</span></span></label></CardContent></Card>
    </div><Card className="h-fit rounded-2xl border-slate-200 shadow-sm xl:sticky xl:top-6"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><ShieldCheck className="h-5 w-5 text-emerald-600" />Resumo das regras</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div><p className="text-slate-500">Ritmo</p><p className="font-medium">{summary.serviceRhythm}</p></div><div><p className="text-slate-500">Janela futura</p><p className="font-medium">{summary.bookingWindow}</p></div><div><p className="text-slate-500">Cancelamento</p><p className="font-medium">{summary.cancellation}</p></div><div><p className="text-slate-500">Proteção</p><p className="font-medium">{summary.overlap}</p></div><Button className="w-full" onClick={() => void save()} disabled={saving}><Save className="mr-2 h-4 w-4" />{saving ? "Salvando..." : "Salvar regras e padrões"}</Button></CardContent></Card></div>
  </SisagPage>;
}
