"use client";
import { useEffect, useMemo, useState } from "react";
import { CalendarClock, Pencil, Power, Save, X } from "lucide-react";
import { ActionFeedback } from "@/components/ui/ActionFeedback";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SisagDataState, SisagPage, SisagPageHeader } from "@/components/sisag";
import { assignmentPeriodLabel, assignmentPrecedenceLabel, assignmentServiceLabel, WEEKDAYS } from "@/modules/scheduling-config/ServiceBookingAssignment.presentation";

type Unit = { id: string; name: string; active: boolean; isDefault?: boolean };
type Service = { id: string; name: string; active?: boolean };
type Professional = { id: string; name: string; serviceIds: string[] };
type Rule = { id: string; unitId: string; unitName: string; serviceId: string | null; serviceName: string | null; professionalId: string; professionalName: string; weekday: number; startTime: string; endTime: string; priority: number; active: boolean };
type Feedback = { type: "success" | "error" | "info"; message: string };
const initial = { unitId: "", serviceId: "", professionalId: "", weekday: 1, startTime: "08:00", endTime: "12:00", priority: 100 };

export default function ServiceAssignmentsPage() {
  const [units, setUnits] = useState<Unit[]>([]); const [services, setServices] = useState<Service[]>([]); const [professionals, setProfessionals] = useState<Professional[]>([]); const [rules, setRules] = useState<Rule[]>([]); const [form, setForm] = useState(initial); const [editingId, setEditingId] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [confirmDeactivate, setConfirmDeactivate] = useState(""); const [feedback, setFeedback] = useState<Feedback | null>(null);
  const eligibleProfessionals = useMemo(() => form.serviceId ? professionals.filter((item) => item.serviceIds.includes(form.serviceId)) : professionals, [professionals, form.serviceId]);
  async function loadRules() { const response = await fetch("/api/v1/scheduling/service-assignments?status=active", { cache: "no-store" }); const body = await response.json().catch(() => null); if (!response.ok || body?.ok !== true) throw new Error("rules"); setRules(body.items ?? []); }
  async function loadProfessionals(unitId: string) { if (!unitId) { setProfessionals([]); return; } const response = await fetch("/api/v1/professionals?unitId=" + encodeURIComponent(unitId), { cache: "no-store" }); const body = await response.json().catch(() => null); if (!response.ok || body?.ok !== true) throw new Error("professionals"); const enriched = await Promise.all((body.items ?? []).map(async (item: { id: string; name: string }) => { const links = await fetch("/api/v1/professionals/" + item.id + "/services", { cache: "no-store" }); const linksBody = await links.json().catch(() => null); return { ...item, serviceIds: (linksBody?.items ?? []).filter((link: { active: boolean }) => link.active).map((link: { serviceId: string }) => link.serviceId) }; })); setProfessionals(enriched); }
  useEffect(() => { void (async () => { try { const [unitsResponse, servicesResponse] = await Promise.all([fetch("/api/v1/me/company/units"), fetch("/api/v1/services")]); const unitBody = await unitsResponse.json(); const serviceBody = await servicesResponse.json(); if (unitBody?.ok !== true || serviceBody?.ok !== true) throw new Error("references"); const activeUnits = (unitBody.items ?? []).filter((item: Unit) => item.active); setUnits(activeUnits); setServices((serviceBody.items ?? serviceBody ?? []).filter((item: Service) => item.active !== false)); const defaultUnit = activeUnits.find((item: Unit) => item.isDefault)?.id ?? activeUnits[0]?.id ?? ""; setForm((current) => ({ ...current, unitId: defaultUnit })); if (defaultUnit) await loadProfessionals(defaultUnit); await loadRules(); } catch { setFeedback({ type: "error", message: "Não foi possível carregar as regras de distribuição." }); } finally { setLoading(false); } })(); }, []);
  async function changeUnit(unitId: string) { setForm((current) => ({ ...current, unitId, professionalId: "" })); try { await loadProfessionals(unitId); } catch { setProfessionals([]); setFeedback({ type: "error", message: "Não foi possível carregar os profissionais deste local." }); } }
  function cancelEdit() { setEditingId(""); setForm((current) => ({ ...initial, unitId: current.unitId })); setFeedback(null); }
  function edit(rule: Rule) { setEditingId(rule.id); setForm({ unitId: rule.unitId, serviceId: rule.serviceId ?? "", professionalId: rule.professionalId, weekday: rule.weekday, startTime: rule.startTime, endTime: rule.endTime, priority: rule.priority }); void loadProfessionals(rule.unitId); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function save() { if (!form.unitId || !form.professionalId) { setFeedback({ type: "error", message: "Selecione o local e o profissional." }); return; } setSaving(true); setFeedback(null); try { const response = await fetch(editingId ? "/api/v1/scheduling/service-assignments/" + editingId : "/api/v1/scheduling/service-assignments", { method: editingId ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, serviceId: form.serviceId || null, active: true }) }); const body = await response.json().catch(() => null); if (!response.ok) { const messages: Record<string, string> = { assignment_conflict: "Já existe uma regra igual para este turno.", professional_not_enabled_for_service: "O profissional não está habilitado para este serviço.", professional_not_available_at_unit: "O profissional não atende neste local." }; throw new Error(messages[body?.error] ?? "Revise os dados informados."); } await loadRules(); const wasEditing = Boolean(editingId); cancelEdit(); setFeedback({ type: "success", message: wasEditing ? "Regra atualizada com sucesso." : "Regra adicionada com sucesso." }); } catch (error) { setFeedback({ type: "error", message: error instanceof Error ? error.message : "Não foi possível salvar." }); } finally { setSaving(false); } }
  async function deactivate(id: string) { if (confirmDeactivate !== id) { setConfirmDeactivate(id); setFeedback({ type: "info", message: "Clique novamente em Desativar para confirmar." }); return; } try { const response = await fetch("/api/v1/scheduling/service-assignments/" + id, { method: "DELETE" }); if (!response.ok) throw new Error(); setConfirmDeactivate(""); await loadRules(); setFeedback({ type: "success", message: "Regra desativada. O histórico foi preservado." }); } catch { setFeedback({ type: "error", message: "Não foi possível desativar esta regra." }); } }
  if (loading) return <SisagPage><SisagDataState state="loading" title="Carregando distribuição por serviço" /></SisagPage>;
  return <SisagPage><SisagPageHeader context={<span className="inline-flex items-center gap-2"><CalendarClock className="h-4 w-4" />Agendamento</span>} title="Profissionais preferenciais por turno" description="Direcione serviços para o profissional mais adequado em cada local, dia e horário." />{feedback ? <ActionFeedback type={feedback.type} message={feedback.message} /> : null}
    <Card className="rounded-2xl border-slate-200 shadow-sm"><CardHeader><CardTitle className="text-lg">{editingId ? "Alterar regra" : "Nova regra"}</CardTitle><CardDescription>Escolha um serviço específico ou deixe em todos os serviços para criar o padrão do turno.</CardDescription></CardHeader><CardContent className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><div><Label>Local</Label><select value={form.unitId} onChange={(event) => void changeUnit(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Selecione</option>{units.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><Label>Serviço</Label><select value={form.serviceId} onChange={(event) => setForm({ ...form, serviceId: event.target.value, professionalId: "" })} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Todos os serviços do turno</option>{services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div><Label>Profissional preferencial</Label><select value={form.professionalId} onChange={(event) => setForm({ ...form, professionalId: event.target.value })} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Selecione</option>{eligibleProfessionals.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><p className="mt-1 text-xs text-slate-500">Somente profissionais habilitados no local{form.serviceId ? " e no serviço" : ""}.</p></div><div><Label>Dia</Label><select value={form.weekday} onChange={(event) => setForm({ ...form, weekday: Number(event.target.value) })} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{WEEKDAYS.map((name, index) => <option key={name} value={index}>{name}</option>)}</select></div><div><Label>Início do turno</Label><Input className="mt-1" type="time" value={form.startTime} onChange={(event) => setForm({ ...form, startTime: event.target.value })} /></div><div><Label>Fim do turno</Label><Input className="mt-1" type="time" value={form.endTime} onChange={(event) => setForm({ ...form, endTime: event.target.value })} /></div><div><Label>Prioridade</Label><Input className="mt-1" type="number" min={1} max={1000} value={form.priority} onChange={(event) => setForm({ ...form, priority: Number(event.target.value) })} /><p className="mt-1 text-xs text-slate-500">Quanto maior, mais cedo a regra será considerada.</p></div><div className="flex items-end justify-end gap-2">{editingId ? <Button variant="outline" onClick={cancelEdit}><X className="mr-2 h-4 w-4" />Cancelar</Button> : null}<Button onClick={() => void save()} disabled={saving}><Save className="mr-2 h-4 w-4" />{saving ? "Salvando..." : editingId ? "Salvar alteração" : "Adicionar regra"}</Button></div></CardContent></Card>
    {rules.length === 0 ? <SisagDataState state="empty" title="Nenhuma regra ativa" description="Sem regras, o sistema seguirá a escolha manual e a disponibilidade dos profissionais." /> : <div className="grid gap-4 lg:grid-cols-2">{rules.map((rule) => <Card key={rule.id} className="rounded-2xl border-slate-200"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-base">{assignmentServiceLabel(rule.serviceName)}</CardTitle><CardDescription>{rule.unitName} · {assignmentPeriodLabel(rule)}</CardDescription></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-700">Ativa</span></div></CardHeader><CardContent className="space-y-3"><div><p className="font-medium text-slate-900">{rule.professionalName}</p><p className="mt-1 text-sm text-slate-600">{assignmentPrecedenceLabel(rule.serviceName)}</p><p className="mt-1 text-xs text-slate-500">Prioridade {rule.priority}</p></div><div className="flex justify-end gap-2 border-t border-slate-100 pt-3"><Button variant="outline" size="sm" onClick={() => edit(rule)}><Pencil className="mr-2 h-4 w-4" />Alterar</Button><Button variant={confirmDeactivate === rule.id ? "destructive" : "outline"} size="sm" onClick={() => void deactivate(rule.id)}><Power className="mr-2 h-4 w-4" />{confirmDeactivate === rule.id ? "Confirmar" : "Desativar"}</Button></div></CardContent></Card>)}</div>}
  </SisagPage>;
}
