"use client";
import { useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { CalendarClock, Plus, Trash2 } from "lucide-react";
import { ActionFeedback } from "@/components/ui/ActionFeedback";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { SisagDataState, SisagPage, SisagPageHeader } from "@/components/sisag";
import { describePeriod, groupAvailability, type AvailabilityPeriod, WEEKDAY_LABELS } from "@/modules/schedules/Schedule.presentation";

type Unit = { unitId: string; unitName: string; active: boolean; isPrimary: boolean };
type Feedback = { type: "success" | "error" | "info"; message: string };
export default function ProfessionalAvailabilityPage() {
  const params = useParams(); const router = useRouter(); const id = params.id as string;
  const [name, setName] = useState(""); const [units, setUnits] = useState<Unit[]>([]); const [periods, setPeriods] = useState<AvailabilityPeriod[]>([]); const [unitId, setUnitId] = useState(""); const [weekday, setWeekday] = useState("1"); const [startTime, setStartTime] = useState("08:00"); const [endTime, setEndTime] = useState("12:00"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [removing, setRemoving] = useState(""); const [pendingRemoval, setPendingRemoval] = useState(""); const [feedback, setFeedback] = useState<Feedback | null>(null);
  const groups = useMemo(() => groupAvailability(periods), [periods]);
  async function load() { setLoading(true); try { const [professionalResponse, unitResponse, scheduleResponse] = await Promise.all([fetch("/api/v1/professionals/" + id), fetch("/api/v1/professionals/" + id + "/units"), fetch("/api/v1/professionals/" + id + "/schedules")]); const professional = await professionalResponse.json(); const unitBody = await unitResponse.json(); const scheduleBody = await scheduleResponse.json(); if (!professionalResponse.ok || unitBody?.ok !== true || scheduleBody?.ok !== true) throw new Error("load"); const activeUnits = (unitBody.items ?? []).filter((item: Unit) => item.active); setName(professional.name ?? "Profissional"); setUnits(activeUnits); setPeriods(scheduleBody.items ?? []); setUnitId((current) => current || activeUnits.find((item: Unit) => item.isPrimary)?.unitId || activeUnits[0]?.unitId || ""); } catch { setFeedback({ type: "error", message: "Não foi possível carregar a disponibilidade do profissional." }); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [id]);
  async function addPeriod() { setSaving(true); setFeedback(null); try { const response = await fetch("/api/v1/professionals/" + id + "/schedules", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ unitId, weekday: Number(weekday), startTime, endTime }) }); const body = await response.json().catch(() => null); if (!response.ok) { if (body?.error === "schedule_conflict") throw new Error("Este período se sobrepõe a outro horário no mesmo local."); if (body?.error === "unit_not_linked") throw new Error("Selecione um local ativo deste profissional."); throw new Error("Revise o dia e os horários informados."); } await load(); setFeedback({ type: "success", message: "Período adicionado à disponibilidade." }); } catch (error) { setFeedback({ type: "error", message: error instanceof Error ? error.message : "Não foi possível adicionar o período." }); } finally { setSaving(false); } }
  async function removePeriod(periodId: string) { if (pendingRemoval !== periodId) { setPendingRemoval(periodId); setFeedback({ type: "info", message: "Clique novamente em Remover para confirmar." }); return; } setRemoving(periodId); try { const response = await fetch("/api/v1/professionals/" + id + "/schedules/" + periodId, { method: "DELETE" }); if (!response.ok) throw new Error("remove"); setPendingRemoval(""); await load(); setFeedback({ type: "success", message: "Período removido da disponibilidade." }); } catch { setFeedback({ type: "error", message: "Não foi possível remover o período." }); } finally { setRemoving(""); } }
  if (loading && periods.length === 0) return <SisagPage><SisagDataState state="loading" title="Carregando disponibilidade" /></SisagPage>;
  return <SisagPage><SisagPageHeader context={<span className="inline-flex items-center gap-2"><CalendarClock className="h-4 w-4" />Agenda semanal</span>} title={"Disponibilidade de " + (name || "profissional")} description="Defina em quais locais, dias e períodos este profissional pode receber agendamentos." />
    {feedback ? <ActionFeedback type={feedback.type} message={feedback.message} /> : null}
    {units.length === 0 ? <SisagDataState state="empty" title="Nenhum local ativo para este profissional" description="Vincule ao menos um local de atendimento antes de configurar a disponibilidade." action={<Button variant="outline" onClick={() => router.push("/admin/professionals/" + id + "/edit")}>Configurar locais</Button>} /> : <Card className="rounded-2xl border-slate-200 shadow-sm"><CardHeader><CardTitle className="text-lg">Adicionar período</CardTitle><CardDescription>Você pode cadastrar manhã, tarde e noite separadamente para o mesmo dia.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-5"><div className="md:col-span-2"><label className="text-sm font-medium">Local de atendimento</label><select value={unitId} onChange={(event) => setUnitId(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{units.map((unit) => <option key={unit.unitId} value={unit.unitId}>{unit.unitName}{unit.isPrimary ? " · principal" : ""}</option>)}</select></div><div><label className="text-sm font-medium">Dia da semana</label><select value={weekday} onChange={(event) => setWeekday(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{WEEKDAY_LABELS.map((label, value) => <option key={label} value={value}>{label}</option>)}</select></div><div><label className="text-sm font-medium">Início</label><Input className="mt-1" type="time" value={startTime} onChange={(event) => setStartTime(event.target.value)} /></div><div><label className="text-sm font-medium">Fim</label><Input className="mt-1" type="time" value={endTime} onChange={(event) => setEndTime(event.target.value)} /></div><div className="md:col-span-5 flex justify-end"><Button onClick={() => void addPeriod()} disabled={saving || !unitId}><Plus className="mr-2 h-4 w-4" />{saving ? "Adicionando..." : "Adicionar período"}</Button></div></CardContent></Card>}
    {groups.length === 0 ? <SisagDataState state="empty" title="Nenhum período configurado" description="Adicione os dias e horários em que o profissional estará disponível." /> : <div className="grid gap-4 lg:grid-cols-2">{groups.map((group) => <Card key={group.weekday} className="rounded-2xl border-slate-200"><CardHeader><CardTitle className="text-base">{group.label}</CardTitle><CardDescription>{group.periods.length} {group.periods.length === 1 ? "período disponível" : "períodos disponíveis"}</CardDescription></CardHeader><CardContent className="space-y-3">{group.periods.map((period) => <div key={period.id} className="flex flex-col gap-3 rounded-xl border border-slate-100 bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-slate-900">{period.startTime} às {period.endTime}</p><p className="text-sm text-slate-500">{period.unitName}</p></div><Button type="button" variant={pendingRemoval === period.id ? "destructive" : "outline"} size="sm" disabled={removing === period.id} aria-label={"Remover " + describePeriod(period)} onClick={() => void removePeriod(period.id)}><Trash2 className="mr-2 h-4 w-4" />{removing === period.id ? "Removendo..." : pendingRemoval === period.id ? "Confirmar remoção" : "Remover"}</Button></div>)}</CardContent></Card>)}</div>}
    <div className="flex justify-end"><Button variant="outline" onClick={() => router.push("/admin/professionals")}>Voltar aos profissionais</Button></div>
  </SisagPage>;
}
