import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { requireApiRole } from "@/lib/auth/apiAuth";
import { ServiceBookingAssignmentInputSchema } from "@/modules/scheduling-config/ServiceBookingAssignment.schema";
import { deactivateServiceBookingAssignment, ServiceBookingAssignmentError, updateServiceBookingAssignment } from "@/modules/scheduling-config/ServiceBookingAssignment.service";
type Context = { params: Promise<{ id: string }> };
async function id(context: Context) { return z.string().uuid().safeParse((await context.params).id); }
function failure(error: unknown) { if (typeof error === "object" && error !== null && "code" in error && error.code === "23505") return NextResponse.json({ ok: false, error: "assignment_conflict" }, { status: 409 }); if (error instanceof ServiceBookingAssignmentError) return NextResponse.json({ ok: false, error: error.code }, { status: error.code === "assignment_not_found" ? 404 : 400 }); console.error("service assignment item API error", error); return NextResponse.json({ ok: false, error: "internal_error" }, { status: 500 }); }
export async function PUT(request: NextRequest, context: Context) { try { const auth = await requireApiRole(request, ["owner", "admin"]); if (auth.ok === false) return auth.response; const parsedId = await id(context); if (!parsedId.success) return NextResponse.json({ ok: false, error: "invalid_assignment_id" }, { status: 400 }); const parsed = ServiceBookingAssignmentInputSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ ok: false, error: "invalid_assignment", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); return NextResponse.json({ ok: true, item: await updateServiceBookingAssignment(auth.auth.companyId, parsedId.data, parsed.data) }); } catch (error) { return failure(error); } }
export async function DELETE(request: NextRequest, context: Context) { try { const auth = await requireApiRole(request, ["owner", "admin"]); if (auth.ok === false) return auth.response; const parsedId = await id(context); if (!parsedId.success) return NextResponse.json({ ok: false, error: "invalid_assignment_id" }, { status: 400 }); return NextResponse.json({ ok: true, item: await deactivateServiceBookingAssignment(auth.auth.companyId, parsedId.data) }); } catch (error) { return failure(error); } }
