"use client";
import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { presentReminderStatus, safeReminderFailureReason } from "@/modules/automation/BookingReminderMonitoring.presentation";
type Activity = { summary: { total: number; pending: number; processing: number; done: number; failed: number }; items: Array<{ id: string; bookingId: string | null; status: string; runAt: string | null; completedAt: string | null; attempts: number; lastError: string | null; clientName: string | null; bookingStartTime: string | null }> };
const format = (value: string | null) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—";
export function BookingReminderActivity() { const [data, setData] = useState<Activity | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(false); try { const response = await fetch("/api/v1/settings/booking-reminders/activity?limit=30", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(); setData(body); } catch { setError(true); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <Card className="rounded-2xl border-slate-200"><CardHeader className="flex-row items-start justify-between gap-4"><div><CardTitle className="text-lg">Operação dos lembretes</CardTitle><CardDescription>Acompanhe programações, envios e falhas recentes.</CardDescription></div><Button variant="outline" size="sm" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "mr-2 h-4 w-4 animate-spin" : "mr-2 h-4 w-4"} />Atualizar</Button></CardHeader><CardContent className="space-y-5">
    {error ? <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">Não foi possível carregar o acompanhamento.</div> : null}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Clock3} label="Programados" value={(data?.summary.pending ?? 0) + (data?.summary.processing ?? 0)} /><Metric icon={CheckCircle2} label="Enviados" value={data?.summary.done ?? 0} /><Metric icon={AlertTriangle} label="Falhas" value={data?.summary.failed ?? 0} /><Metric icon={Clock3} label="Total" value={data?.summary.total ?? 0} /></div>
    {!loading && data?.items.length === 0 ? <p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-600">Nenhum lembrete foi programado ainda.</p> : null}
    {data?.items.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-xs uppercase tracking-wide text-slate-500"><th className="px-3 py-3">Cliente</th><th className="px-3 py-3">Atendimento</th><th className="px-3 py-3">Execução</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Tentativas</th><th className="px-3 py-3">Observação</th></tr></thead><tbody>{data.items.map((item) => { const status = presentReminderStatus(item.status); return <tr key={item.id} className="border-b border-slate-100"><td className="px-3 py-3 font-medium text-slate-900">{item.clientName || "Cliente"}</td><td className="px-3 py-3 text-slate-600">{format(item.bookingStartTime)}</td><td className="px-3 py-3 text-slate-600">{format(item.completedAt || item.runAt)}</td><td className="px-3 py-3"><span className={"inline-flex rounded-full px-2.5 py-1 text-xs font-medium " + status.tone}>{status.label}</span></td><td className="px-3 py-3 text-slate-600">{item.attempts}</td><td className="max-w-xs px-3 py-3 text-slate-600">{safeReminderFailureReason(item.lastError) || "—"}</td></tr>; })}</tbody></table></div> : null}
  </CardContent></Card>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Clock3; label: string; value: number }) { return <div className="rounded-xl border border-slate-200 p-4"><Icon className="h-4 w-4 text-slate-500" /><p className="mt-3 text-2xl font-semibold text-slate-900">{value}</p><p className="text-xs text-slate-500">{label}</p></div>; }
