"use client";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, RefreshCcw, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
type Slot = { startTime: string; endTime: string; professionalId: string; professionalName: string; assignment: "specific" | "shift" | "available" };
type Props = { unitId: string; serviceId: string; date: string; selectedSlot?: string | null; onSelect: (selection: { time: string; professionalId: string; professionalName: string }) => void };
function time(value: string, timezone: string) { return new Intl.DateTimeFormat("pt-BR", { timeZone: timezone, hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date(value)); }
export function ServiceLedSlotPicker({ unitId, serviceId, date, selectedSlot, onSelect }: Props) {
  const [slots, setSlots] = useState<Slot[]>([]); const [timezone, setTimezone] = useState("America/Sao_Paulo"); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const query = useMemo(() => new URLSearchParams({ unitId, serviceId, date }).toString(), [unitId, serviceId, date]);
  async function load() { if (!unitId || !serviceId || !date) { setSlots([]); return; } setLoading(true); setError(""); try { const response = await fetch("/api/v1/scheduling/service-available?" + query, { cache: "no-store" }); const body = await response.json().catch(() => null); if (!response.ok || body?.ok !== true) throw new Error(body?.error ?? "load"); setSlots(body.slots ?? []); setTimezone(body.timezone ?? "America/Sao_Paulo"); } catch { setSlots([]); setError("Não foi possível calcular os horários por serviço."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [query]);
  if (!unitId || !serviceId) return <div className="rounded-xl border border-dashed border-slate-300 bg-white p-4 text-sm text-slate-500">Selecione o local e o serviço para visualizar os horários.</div>;
  return <div className="space-y-4"><div className="flex items-start justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4"><div><h3 className="flex items-center gap-2 text-sm font-semibold text-slate-900"><Clock3 className="h-4 w-4" />Horários disponíveis por serviço</h3><p className="mt-1 text-sm text-slate-500">O sistema associa cada horário ao profissional mais adequado e disponível.</p></div><Button type="button" variant="outline" size="sm" onClick={() => void load()} disabled={loading}><RefreshCcw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />Atualizar</Button></div>{loading ? <div className="rounded-xl border p-4 text-sm text-slate-500">Calculando horários...</div> : null}{!loading && error ? <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div> : null}{!loading && !error && slots.length === 0 ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-700">Não encontramos horários para esta data.</div> : null}{!loading && slots.length > 0 ? <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{slots.map((slot) => { const label = time(slot.startTime, timezone); const active = selectedSlot === label; return <Button key={slot.startTime + slot.professionalId} type="button" variant={active ? "default" : "outline"} className="h-auto min-h-14 justify-start px-3 py-2" onClick={() => onSelect({ time: label, professionalId: slot.professionalId, professionalName: slot.professionalName })}><span className="flex w-full items-center justify-between gap-3"><span className="font-semibold">{label}</span><span className="inline-flex min-w-0 items-center gap-1 text-xs opacity-80"><UserRound className="h-3.5 w-3.5" />{slot.professionalName}</span>{active ? <CheckCircle2 className="h-4 w-4" /> : null}</span></Button>; })}</div> : null}</div>;
}
