"use client";
import { useEffect, useMemo, useState } from "react";
import { BellRing, Save } from "lucide-react";
import { ActionFeedback } from "@/components/ui/ActionFeedback";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SisagDataState, SisagPage, SisagPageHeader } from "@/components/sisag";
import { DEFAULT_BOOKING_REMINDER_TEMPLATE, type BookingReminderSettings } from "@/modules/automation/BookingReminderSettings.schema";

const defaults: BookingReminderSettings = { enabled: false, hoursBefore: 24, template: DEFAULT_BOOKING_REMINDER_TEMPLATE };
export default function BookingReminderSettingsPage() {
  const [form, setForm] = useState(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [feedback, setFeedback] = useState<{ type: "success" | "error"; message: string } | null>(null);
  useEffect(() => { fetch("/api/v1/settings/booking-reminders", { cache: "no-store" }).then((r) => r.json()).then((body) => { if (body?.settings) setForm(body.settings); else throw new Error(); }).catch(() => setFeedback({ type: "error", message: "Não foi possível carregar os lembretes." })).finally(() => setLoading(false)); }, []);
  const preview = useMemo(() => form.template.replaceAll("{{nome}}", "Ana").replaceAll("{{data_hora}}", "10/09/2026 às 14:30"), [form.template]);
  async function save() { setSaving(true); setFeedback(null); try { const response = await fetch("/api/v1/settings/booking-reminders", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(); setForm(body.settings); setFeedback({ type: "success", message: "Lembretes atualizados. Novos agendamentos já usarão esta regra." }); } catch { setFeedback({ type: "error", message: "Não foi possível salvar. Revise a antecedência e a mensagem." }); } finally { setSaving(false); } }
  if (loading) return <SisagPage><SisagDataState state="loading" title="Carregando lembretes" /></SisagPage>;
  return <SisagPage><SisagPageHeader context={<span className="inline-flex items-center gap-2"><BellRing className="h-4 w-4" />Automação</span>} title="Lembretes de agendamento" description="Reduza esquecimentos com uma mensagem automática antes do atendimento." />
    {feedback ? <ActionFeedback type={feedback.type} message={feedback.message} /> : null}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="space-y-5"><Card className={form.enabled ? "rounded-2xl border-emerald-200 bg-emerald-50/40" : "rounded-2xl border-slate-200"}><CardContent className="p-5"><label className="flex items-start gap-3"><input type="checkbox" className="mt-1 h-4 w-4" checked={form.enabled} onChange={(event) => setForm((current) => ({ ...current, enabled: event.target.checked }))} /><span><strong className="block text-sm text-slate-900">Enviar lembrete automático pelo WhatsApp</strong><span className="mt-1 block text-sm text-slate-600">O envio ocorre somente para agendamentos ativos e clientes com WhatsApp.</span></span></label></CardContent></Card>
      <Card className="rounded-2xl border-slate-200"><CardHeader><CardTitle className="text-lg">Quando enviar</CardTitle><CardDescription>Escolha uma antecedência entre 1 hora e 7 dias.</CardDescription></CardHeader><CardContent><Label htmlFor="hoursBefore">Horas antes do atendimento</Label><Input id="hoursBefore" className="mt-1 max-w-xs" type="number" min={1} max={168} value={form.hoursBefore} onChange={(event) => setForm((current) => ({ ...current, hoursBefore: Number(event.target.value) }))} /></CardContent></Card>
      <Card className="rounded-2xl border-slate-200"><CardHeader><CardTitle className="text-lg">Mensagem</CardTitle><CardDescription>Use {"{{nome}}"} e {"{{data_hora}}"} para personalizar automaticamente.</CardDescription></CardHeader><CardContent><Label htmlFor="template">Texto do lembrete</Label><textarea id="template" rows={7} maxLength={600} className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.template} onChange={(event) => setForm((current) => ({ ...current, template: event.target.value }))} /><div className="mt-3 flex justify-between text-xs text-slate-500"><button type="button" className="underline" onClick={() => setForm((current) => ({ ...current, template: DEFAULT_BOOKING_REMINDER_TEMPLATE }))}>Restaurar mensagem padrão</button><span>{form.template.length}/600</span></div></CardContent></Card></div>
      <Card className="h-fit rounded-2xl border-slate-200 xl:sticky xl:top-6"><CardHeader><CardTitle className="text-lg">Prévia no WhatsApp</CardTitle></CardHeader><CardContent><div className="rounded-2xl rounded-tr-sm bg-emerald-100 p-4 text-sm leading-6 text-slate-800 shadow-sm">{preview}</div><p className="mt-4 text-xs text-slate-500">{form.enabled ? `Envio programado ${form.hoursBefore} hora(s) antes.` : "Envio automático desativado."}</p><Button className="mt-5 w-full" disabled={saving || form.template.trim().length < 20} onClick={() => void save()}><Save className="mr-2 h-4 w-4" />{saving ? "Salvando..." : "Salvar lembretes"}</Button></CardContent></Card></div>
  </SisagPage>;
}
