import { and, desc, eq, gte } from "drizzle-orm";
import { automationJobs, bookingEvents, bookingFeedbacks, bookings } from "@/drizzle/schema";
import { getDb } from "@/lib/db";
export function readFollowupScore(text: string): number | null { const value = text.trim(); return /^[1-5]$/.test(value) ? Number(value) : null; }
export class BookingFollowupFeedbackService {
  static async handle(input: { companyId: string; clientId: string; text: string; correlationId?: string | null; now?: Date }) { const score = readFollowupScore(input.text); if (!score) return { handled: false as const }; const db = getDb(); const now = input.now ?? new Date(); const recent = new Date(now.getTime() - 30 * 24 * 60 * 60_000);
    const rows = await db.select({ jobId: automationJobs.id, outboxId: automationJobs.outboxId, bookingId: bookings.id }).from(automationJobs).innerJoin(bookings, eq(bookings.id, automationJobs.bookingId)).where(and(eq(automationJobs.companyId, input.companyId), eq(automationJobs.clientId, input.clientId), eq(automationJobs.type, "followup"), eq(automationJobs.status, "done"), eq(bookings.companyId, input.companyId), eq(bookings.status, "COMPLETED"), gte(automationJobs.completedAt, recent))).orderBy(desc(automationJobs.completedAt)).limit(1); const target = rows[0]; if (!target) return { handled: false as const };
    const existing = await db.select({ id: bookingFeedbacks.id, score: bookingFeedbacks.score }).from(bookingFeedbacks).where(and(eq(bookingFeedbacks.companyId, input.companyId), eq(bookingFeedbacks.bookingId, target.bookingId))).limit(1);
    if (existing[0]?.score === score) return { handled: true as const, applied: false as const, bookingId: target.bookingId, score, replyText: "Obrigado! Sua avaliação já estava registrada. 💙" };
    await db.transaction(async (tx) => { await tx.insert(bookingFeedbacks).values({ companyId: input.companyId, bookingId: target.bookingId, clientId: input.clientId, score, source: "whatsapp", correlationId: input.correlationId ?? null }).onConflictDoUpdate({ target: [bookingFeedbacks.companyId, bookingFeedbacks.bookingId], set: { score, correlationId: input.correlationId ?? null, updatedAt: now } }); await tx.insert(bookingEvents).values({ companyId: input.companyId, bookingId: target.bookingId, clientId: input.clientId, outboxId: target.outboxId, type: "automation.booking_followup.responded", actor: "whatsapp", payload: { score, source: "booking_followup", followupJobId: target.jobId, correlationId: input.correlationId ?? null, respondedAt: now.toISOString(), updated: Boolean(existing[0]) } }); });
    const replyText = score <= 2 ? "Obrigado pela sinceridade. Sentimos que sua experiência não foi a esperada e nossa equipe poderá entrar em contato." : score === 3 ? "Obrigado pela avaliação! Seu retorno nos ajuda a melhorar." : "Obrigado pela avaliação! Ficamos felizes com sua experiência. 💙";
    return { handled: true as const, applied: true as const, bookingId: target.bookingId, score, needsRecovery: score <= 2, replyText };
  }
}
