import { and, desc, eq, gte, inArray } from "drizzle-orm";
import { bookingEvents, bookingRecoveryCases, bookingRecoveryDrafts, bookingRecoveryResponses } from "@/drizzle/schema"; import { getDb } from "@/lib/db";
export type RecoveryResponseClassification = "positive" | "negative" | "human_request" | "other";
export function classifyRecoveryResponse(text: string): RecoveryResponseClassification { const value = text.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim(); if (/\b(atendente|humano|pessoa|ligue|ligar|quero falar|falar com)\b/.test(value)) return "human_request"; if (/\b(pessimo|horrivel|ruim|reclamacao|nao resolveu|insatisfeito|insatisfeita)\b/.test(value)) return "negative"; if (/\b(obrigado|obrigada|resolvido|resolvida|tudo certo|melhorou|satisfeito|satisfeita)\b/.test(value)) return "positive"; return "other"; }
const acknowledgement = "Recebemos sua mensagem. Uma pessoa da nossa equipe continuará este atendimento com você.";
export class BookingRecoveryResponseService { static async handle(input: { companyId: string; clientId: string; text: string; correlationId?: string | null; now?: Date }) { const providerMessageId = input.correlationId?.trim(); const message = input.text.trim(); if (!providerMessageId || !message) return { handled: false as const }; const db = getDb(); const now = input.now ?? new Date(); const recent = new Date(now.getTime() - 14 * 24 * 60 * 60_000);
    const targets = await db.select({ caseId: bookingRecoveryCases.id, caseStatus: bookingRecoveryCases.status, priority: bookingRecoveryCases.priority, bookingId: bookingRecoveryCases.bookingId, clientId: bookingRecoveryCases.clientId, draftId: bookingRecoveryDrafts.id }).from(bookingRecoveryDrafts).innerJoin(bookingRecoveryCases, and(eq(bookingRecoveryCases.id, bookingRecoveryDrafts.recoveryCaseId), eq(bookingRecoveryCases.companyId, input.companyId))).where(and(eq(bookingRecoveryDrafts.companyId, input.companyId), eq(bookingRecoveryDrafts.clientId, input.clientId), eq(bookingRecoveryDrafts.status, "sent"), gte(bookingRecoveryDrafts.sentAt, recent), inArray(bookingRecoveryCases.status, ["open", "contacted"]))).orderBy(desc(bookingRecoveryDrafts.sentAt)).limit(1); const target = targets[0]; if (!target) return { handled: false as const };
    const existing = await db.select({ id: bookingRecoveryResponses.id }).from(bookingRecoveryResponses).where(and(eq(bookingRecoveryResponses.companyId, input.companyId), eq(bookingRecoveryResponses.providerMessageId, providerMessageId))).limit(1); if (existing[0]) return { handled: true as const, applied: false as const, replyText: acknowledgement };
    const classification = classifyRecoveryResponse(message); const needsAttention = target.priority === "urgent" || classification === "negative" || classification === "human_request" || classification === "other";
    await db.transaction(async (tx) => { const inserted = await tx.insert(bookingRecoveryResponses).values({ companyId: input.companyId, recoveryCaseId: target.caseId, draftId: target.draftId, bookingId: target.bookingId, clientId: target.clientId, providerMessageId, message, classification, needsAttention }).onConflictDoNothing({ target: [bookingRecoveryResponses.companyId, bookingRecoveryResponses.providerMessageId] }).returning({ id: bookingRecoveryResponses.id }); if (!inserted[0]) return; await tx.update(bookingRecoveryCases).set({ status: "contacted", updatedAt: now }).where(and(eq(bookingRecoveryCases.id, target.caseId), eq(bookingRecoveryCases.companyId, input.companyId), inArray(bookingRecoveryCases.status, ["open", "contacted"]))); await tx.insert(bookingEvents).values({ companyId: input.companyId, bookingId: target.bookingId, clientId: target.clientId, type: "automation.booking_recovery.responded", actor: "whatsapp", payload: { recoveryCaseId: target.caseId, draftId: target.draftId, responseId: inserted[0].id, providerMessageId, classification, needsAttention, receivedAt: now.toISOString() } }); if (needsAttention) await tx.insert(bookingEvents).values({ companyId: input.companyId, bookingId: target.bookingId, clientId: target.clientId, type: "automation.booking_recovery.alert_requested", actor: "system", payload: { recoveryCaseId: target.caseId, responseId: inserted[0].id, priority: target.priority, classification, reason: classification === "positive" ? "urgent_case_response" : "human_review_required", requestedAt: now.toISOString() } }); });
    return { handled: true as const, applied: true as const, classification, needsAttention, replyText: acknowledgement };
  } }
