import { and, eq, inArray } from "drizzle-orm";
import { automationJobs, automationRules, bookings, clients } from "@/drizzle/schema";
import { getDb } from "@/lib/db";
export function calculateFollowupRunAt(completedAt: Date, hoursAfter: number) { return new Date(completedAt.getTime() + Math.min(Math.max(hoursAfter, 0), 720) * 60 * 60_000); }
export function bookingFollowupDedupeKey(bookingId: string, completedAt: Date) { return `booking-followup:${bookingId}:${completedAt.toISOString()}`; }
export class BookingFollowupPlannerService {
  static async plan(input: { companyId: string; bookingId: string; now?: Date }) { const db = getDb(); const rows = await db.select({ bookingId: bookings.id, companyId: bookings.companyId, clientId: bookings.clientId, status: bookings.status, completedAt: bookings.completedAt, clientPhone: clients.phoneE164, clientName: clients.name, enabled: automationRules.enableFollowup, hoursAfter: automationRules.followupHoursAfter, templates: automationRules.templates }).from(bookings).innerJoin(clients, eq(clients.id, bookings.clientId)).leftJoin(automationRules, eq(automationRules.companyId, bookings.companyId)).where(and(eq(bookings.id, input.bookingId), eq(bookings.companyId, input.companyId))).limit(1); const booking = rows[0];
    if (!booking) return { ok: false as const, error: "booking_not_found" as const };
    if (!booking.enabled) return { ok: true as const, scheduled: false as const, reason: "automation_disabled" as const };
    if (booking.status !== "COMPLETED" || !booking.completedAt) return { ok: true as const, scheduled: false as const, reason: "booking_not_completed" as const };
    if (!booking.clientPhone) return { ok: true as const, scheduled: false as const, reason: "client_without_phone" as const };
    const completedAt = new Date(booking.completedAt); const runAt = calculateFollowupRunAt(completedAt, booking.hoursAfter ?? 24); const now = input.now ?? new Date(); if (runAt.getTime() < now.getTime()) return { ok: true as const, scheduled: false as const, reason: "followup_window_passed" as const };
    const dedupeKey = bookingFollowupDedupeKey(booking.bookingId, completedAt);
    await db.update(automationJobs).set({ status: "cancelled", lastError: "Substituído por novo planejamento de follow-up", lockedAt: null, updatedAt: now }).where(and(eq(automationJobs.companyId, input.companyId), eq(automationJobs.bookingId, input.bookingId), eq(automationJobs.type, "followup"), inArray(automationJobs.status, ["pending", "failed"])));
    const inserted = await db.insert(automationJobs).values({ companyId: booking.companyId, bookingId: booking.bookingId, clientId: booking.clientId, type: "followup", status: "pending", runAt, dedupeKey, payload: { channel: "whatsapp", toPhone: booking.clientPhone, clientName: booking.clientName, bookingCompletedAt: completedAt.toISOString(), template: (booking.templates as any)?.bookingFollowup ?? null } }).onConflictDoNothing({ target: automationJobs.dedupeKey }).returning({ id: automationJobs.id });
    return { ok: true as const, scheduled: true as const, jobId: inserted[0]?.id ?? null, dedupeKey, runAt: runAt.toISOString(), reused: inserted.length === 0 };
  }
  static async cancel(input: { companyId: string; bookingId: string; reason: string }) { const rows = await getDb().update(automationJobs).set({ status: "cancelled", lastError: input.reason, lockedAt: null, updatedAt: new Date() }).where(and(eq(automationJobs.companyId, input.companyId), eq(automationJobs.bookingId, input.bookingId), eq(automationJobs.type, "followup"), inArray(automationJobs.status, ["pending", "failed", "processing"]))).returning({ id: automationJobs.id }); return { ok: true as const, cancelled: rows.length }; }
  static async planSafely(input: { companyId: string; bookingId: string }) { try { return await this.plan(input); } catch (error) { console.error("Booking follow-up planning failed", { ...input, error }); return { ok: false as const, error: "planning_failed" as const }; } }
  static async cancelSafely(input: { companyId: string; bookingId: string; reason: string }) { try { return await this.cancel(input); } catch (error) { console.error("Booking follow-up cancellation failed", { ...input, error }); return { ok: false as const, error: "cancellation_failed" as const }; } }
}
