import { eq } from "drizzle-orm";
import { automationRules } from "@/drizzle/schema";
import { getDb } from "@/lib/db";
import { BookingFollowupSettingsSchema, DEFAULT_BOOKING_FOLLOWUP_TEMPLATE, type BookingFollowupSettings } from "./BookingFollowupSettings.schema";
function view(row?: { enableFollowup: boolean; followupHoursAfter: number; templates: unknown } | null): BookingFollowupSettings { const templates = row?.templates && typeof row.templates === "object" ? row.templates as Record<string, unknown> : {}; return { enabled: row?.enableFollowup ?? false, hoursAfter: row?.followupHoursAfter ?? 24, template: typeof templates.bookingFollowup === "string" ? templates.bookingFollowup : DEFAULT_BOOKING_FOLLOWUP_TEMPLATE }; }
export class BookingFollowupSettingsService {
  static async get(companyId: string) { const rows = await getDb().select({ enableFollowup: automationRules.enableFollowup, followupHoursAfter: automationRules.followupHoursAfter, templates: automationRules.templates }).from(automationRules).where(eq(automationRules.companyId, companyId)).limit(1); return view(rows[0]); }
  static async save(companyId: string, input: unknown) { const settings = BookingFollowupSettingsSchema.parse(input); const db = getDb(); const current = await db.select({ templates: automationRules.templates }).from(automationRules).where(eq(automationRules.companyId, companyId)).limit(1); const templates = current[0]?.templates && typeof current[0].templates === "object" ? current[0].templates as Record<string, unknown> : {}; const rows = await db.insert(automationRules).values({ companyId, enableFollowup: settings.enabled, followupHoursAfter: settings.hoursAfter, templates: { ...templates, bookingFollowup: settings.template } }).onConflictDoUpdate({ target: automationRules.companyId, set: { enableFollowup: settings.enabled, followupHoursAfter: settings.hoursAfter, templates: { ...templates, bookingFollowup: settings.template }, updatedAt: new Date() } }).returning({ enableFollowup: automationRules.enableFollowup, followupHoursAfter: automationRules.followupHoursAfter, templates: automationRules.templates }); return view(rows[0]); }
}
