import { and, desc, eq, inArray, sql } from "drizzle-orm";
import { bookingEvents, bookingRecoveryCases, bookingRecoveryDrafts, bookingRecoveryRecommendations, bookings, clients } from "@/drizzle/schema";
import { getDb } from "@/lib/db";
import type { BookingRecoveryAction } from "./BookingRecoveryManagement.schema";
const activeStatuses = ["open", "contacted"] as const;
export class BookingRecoveryManagementService {
  static async list(companyId: string, status = "active") { const db = getDb(); const statusClause = status === "active" ? inArray(bookingRecoveryCases.status, [...activeStatuses]) : status === "all" ? undefined : eq(bookingRecoveryCases.status, status); const where = statusClause ? and(eq(bookingRecoveryCases.companyId, companyId), statusClause) : eq(bookingRecoveryCases.companyId, companyId);
    const [items, summaryRows] = await Promise.all([
      db.select({ id: bookingRecoveryCases.id, bookingId: bookingRecoveryCases.bookingId, clientId: bookingRecoveryCases.clientId, clientName: clients.name, clientPhone: clients.phoneE164, score: bookingRecoveryCases.score, priority: bookingRecoveryCases.priority, status: bookingRecoveryCases.status, assignedTo: bookingRecoveryCases.assignedTo, openedAt: bookingRecoveryCases.openedAt, contactedAt: bookingRecoveryCases.contactedAt, resolvedAt: bookingRecoveryCases.resolvedAt, resolutionNote: bookingRecoveryCases.resolutionNote, bookingStartTime: bookings.startTime, draftStatus: bookingRecoveryDrafts.status, draftMessage: bookingRecoveryDrafts.message, draftRationale: bookingRecoveryDrafts.rationale, draftVersion: bookingRecoveryDrafts.version, recommendationVersion: bookingRecoveryRecommendations.version, recommendationAction: bookingRecoveryRecommendations.suggestedAction, recommendationPriority: bookingRecoveryRecommendations.suggestedPriority, recommendationConfidence: bookingRecoveryRecommendations.confidence, recommendationRationale: bookingRecoveryRecommendations.rationale, recommendationStatus: bookingRecoveryRecommendations.status }).from(bookingRecoveryCases).innerJoin(bookings, and(eq(bookings.id, bookingRecoveryCases.bookingId), eq(bookings.companyId, companyId))).innerJoin(clients, eq(clients.id, bookingRecoveryCases.clientId)).leftJoin(bookingRecoveryDrafts, and(eq(bookingRecoveryDrafts.recoveryCaseId, bookingRecoveryCases.id), eq(bookingRecoveryDrafts.companyId, companyId))).leftJoin(bookingRecoveryRecommendations, and(eq(bookingRecoveryRecommendations.recoveryCaseId, bookingRecoveryCases.id), eq(bookingRecoveryRecommendations.companyId, companyId))).where(where).orderBy(sql`case when ${bookingRecoveryCases.priority} = 'urgent' then 0 else 1 end`, bookingRecoveryCases.openedAt).limit(100),
      db.select({ active: sql<number>`count(*) filter (where ${bookingRecoveryCases.status} in ('open','contacted'))`, urgent: sql<number>`count(*) filter (where ${bookingRecoveryCases.status} in ('open','contacted') and ${bookingRecoveryCases.priority} = 'urgent')`, contacted: sql<number>`count(*) filter (where ${bookingRecoveryCases.status} = 'contacted')`, resolved: sql<number>`count(*) filter (where ${bookingRecoveryCases.status} = 'resolved')` }).from(bookingRecoveryCases).where(eq(bookingRecoveryCases.companyId, companyId)),
    ]); const summary = summaryRows[0]; return { items: items.map((item) => ({ ...item, openedAt: item.openedAt.toISOString(), contactedAt: item.contactedAt?.toISOString() ?? null, resolvedAt: item.resolvedAt?.toISOString() ?? null, bookingStartTime: item.bookingStartTime.toISOString() })), summary: { active: Number(summary?.active ?? 0), urgent: Number(summary?.urgent ?? 0), contacted: Number(summary?.contacted ?? 0), resolved: Number(summary?.resolved ?? 0) } };
  }
  static async apply(input: { companyId: string; caseId: string; actorId: string; command: BookingRecoveryAction }) { const db = getDb(); return db.transaction(async (tx) => { const rows = await tx.select({ id: bookingRecoveryCases.id, bookingId: bookingRecoveryCases.bookingId, clientId: bookingRecoveryCases.clientId, status: bookingRecoveryCases.status, assignedTo: bookingRecoveryCases.assignedTo }).from(bookingRecoveryCases).where(and(eq(bookingRecoveryCases.id, input.caseId), eq(bookingRecoveryCases.companyId, input.companyId))).limit(1); const current = rows[0]; if (!current) return { ok: false as const, error: "recovery_case_not_found" as const }; if (!activeStatuses.includes(current.status as any)) return { ok: false as const, error: "recovery_case_closed" as const };
      const now = new Date(); const action = input.command.action; const nextStatus = action === "contacted" ? "contacted" : action === "resolve" ? "resolved" : action === "dismiss" ? "dismissed" : current.status; const set = action === "claim" ? { assignedTo: input.actorId, updatedAt: now } : action === "contacted" ? { assignedTo: current.assignedTo ?? input.actorId, status: nextStatus, contactedAt: now, updatedAt: now } : { assignedTo: current.assignedTo ?? input.actorId, status: nextStatus, resolvedAt: now, resolutionNote: input.command.note!, updatedAt: now };
      const updated = await tx.update(bookingRecoveryCases).set(set).where(and(eq(bookingRecoveryCases.id, input.caseId), eq(bookingRecoveryCases.companyId, input.companyId), inArray(bookingRecoveryCases.status, [...activeStatuses]))).returning({ id: bookingRecoveryCases.id, status: bookingRecoveryCases.status, assignedTo: bookingRecoveryCases.assignedTo }); if (!updated[0]) return { ok: false as const, error: "concurrent_recovery_change" as const };
      await tx.insert(bookingEvents).values({ companyId: input.companyId, bookingId: current.bookingId, clientId: current.clientId, type: action === "resolve" || action === "dismiss" ? "automation.booking_recovery.closed" : "automation.booking_recovery.updated", actor: "admin", payload: { recoveryCaseId: current.id, action, previousStatus: current.status, status: nextStatus, actorId: input.actorId, note: input.command.note ?? null, occurredAt: now.toISOString() } }); return { ok: true as const, recoveryCase: updated[0] };
    }); }
}
