import { and, asc, eq, gte, inArray, isNull, lte, or, sql } from "drizzle-orm";
import { bookingRecoveryCases, bookingRecoveryDrafts, bookingRecoveryResponses, clients } from "@/drizzle/schema"; import { getDb } from "@/lib/db";
export function outcomePercentage(value: number, total: number) { return total > 0 ? Number(((value / total) * 100).toFixed(1)) : 0; }
export function averageDurationMinutes(values: number[]) { return values.length ? Math.round(values.reduce((sum,value)=>sum+value,0)/values.length) : 0; }
export class BookingRecoveryOutcomesService { static async get(input:{companyId:string;days?:number;slaHours?:number;now?:Date}) { const db=getDb(); const now=input.now??new Date(); const days=Math.min(Math.max(input.days??30,1),365); const slaHours=Math.min(Math.max(input.slaHours??4,1),72); const from=new Date(now.getTime()-days*24*60*60_000); const slaLimit=new Date(now.getTime()-slaHours*60*60_000);
    const [contacts,cases,pendingSla,activeRows]=await Promise.all([
      db.select({id:bookingRecoveryDrafts.id,sentAt:bookingRecoveryDrafts.sentAt}).from(bookingRecoveryDrafts).where(and(eq(bookingRecoveryDrafts.companyId,input.companyId),eq(bookingRecoveryDrafts.status,"sent"),gte(bookingRecoveryDrafts.sentAt,from),lte(bookingRecoveryDrafts.sentAt,now))).orderBy(asc(bookingRecoveryDrafts.sentAt)).limit(5000),
      db.select({id:bookingRecoveryCases.id,status:bookingRecoveryCases.status,priority:bookingRecoveryCases.priority,openedAt:bookingRecoveryCases.openedAt,resolvedAt:bookingRecoveryCases.resolvedAt}).from(bookingRecoveryCases).where(and(eq(bookingRecoveryCases.companyId,input.companyId),or(gte(bookingRecoveryCases.openedAt,from),gte(bookingRecoveryCases.resolvedAt,from)))).limit(5000),
      db.select({id:bookingRecoveryResponses.id,recoveryCaseId:bookingRecoveryResponses.recoveryCaseId,clientName:clients.name,message:bookingRecoveryResponses.message,classification:bookingRecoveryResponses.classification,createdAt:bookingRecoveryResponses.createdAt,priority:bookingRecoveryCases.priority}).from(bookingRecoveryResponses).innerJoin(bookingRecoveryCases,and(eq(bookingRecoveryCases.id,bookingRecoveryResponses.recoveryCaseId),eq(bookingRecoveryCases.companyId,input.companyId))).innerJoin(clients,eq(clients.id,bookingRecoveryResponses.clientId)).where(and(eq(bookingRecoveryResponses.companyId,input.companyId),isNull(bookingRecoveryResponses.acknowledgedAt),gte(bookingRecoveryResponses.createdAt,from),lte(bookingRecoveryResponses.createdAt,slaLimit))).orderBy(asc(bookingRecoveryResponses.createdAt)).limit(50),
      db.select({count:sql<number>`count(*)`}).from(bookingRecoveryCases).where(and(eq(bookingRecoveryCases.companyId,input.companyId),inArray(bookingRecoveryCases.status,["open","contacted"]))),
    ]);
    const contactIds=contacts.map(item=>item.id); const responses=contactIds.length?await db.select({draftId:bookingRecoveryResponses.draftId,classification:bookingRecoveryResponses.classification,createdAt:bookingRecoveryResponses.createdAt,acknowledgedAt:bookingRecoveryResponses.acknowledgedAt}).from(bookingRecoveryResponses).where(and(eq(bookingRecoveryResponses.companyId,input.companyId),inArray(bookingRecoveryResponses.draftId,contactIds),lte(bookingRecoveryResponses.createdAt,now))).orderBy(asc(bookingRecoveryResponses.createdAt)).limit(10000):[];
    const contactById=new Map(contacts.map(item=>[item.id,item])); const firstByDraft=new Map<string,(typeof responses)[number]>(); for(const response of responses) if(!firstByDraft.has(response.draftId)) firstByDraft.set(response.draftId,response); const firstResponses=[...firstByDraft.values()]; const responseMinutes=firstResponses.map(response=>{const sent=contactById.get(response.draftId)?.sentAt;return sent?Math.max(0,(response.createdAt.getTime()-sent.getTime())/60_000):0}); const acknowledgeMinutes=responses.filter(item=>item.acknowledgedAt).map(item=>Math.max(0,(item.acknowledgedAt!.getTime()-item.createdAt.getTime())/60_000)); const classifications=["positive","negative","human_request","other"].map(classification=>({classification,count:responses.filter(item=>item.classification===classification).length})); const opened=cases.filter(item=>item.openedAt>=from).length; const resolved=cases.filter(item=>item.status==="resolved"&&item.resolvedAt&&item.resolvedAt>=from).length; const dismissed=cases.filter(item=>item.status==="dismissed"&&item.resolvedAt&&item.resolvedAt>=from).length;
    return {period:{days,slaHours,from:from.toISOString(),to:now.toISOString()},summary:{contacts:contacts.length,responded:firstResponses.length,responseRate:outcomePercentage(firstResponses.length,contacts.length),averageResponseMinutes:averageDurationMinutes(responseMinutes),averageAcknowledgementMinutes:averageDurationMinutes(acknowledgeMinutes),opened,resolved,dismissed,resolutionRate:outcomePercentage(resolved,opened),active:Number(activeRows[0]?.count??0),outsideSla:pendingSla.length},classifications,pendingSla:pendingSla.map(item=>({...item,createdAt:item.createdAt.toISOString(),waitingMinutes:Math.floor((now.getTime()-item.createdAt.getTime())/60_000)}))};
  } }
