import { and, desc, eq, gte, lte, sql } from "drizzle-orm";
import { bookingFeedbacks, bookings, clients } from "@/drizzle/schema";
import { getDb } from "@/lib/db";
export class BookingFollowupInsightsService {
  static async get(input: { companyId: string; days?: number; now?: Date }) { const days = [7, 30, 90].includes(input.days ?? 30) ? input.days ?? 30 : 30; const now = input.now ?? new Date(); const from = new Date(now.getTime() - days * 24 * 60 * 60_000); const db = getDb(); const [summaryRows, recovery] = await Promise.all([
      db.select({ total: sql<number>`count(*)`, average: sql<number>`coalesce(avg(${bookingFeedbacks.score}), 0)`, score1: sql<number>`count(*) filter (where ${bookingFeedbacks.score} = 1)`, score2: sql<number>`count(*) filter (where ${bookingFeedbacks.score} = 2)`, score3: sql<number>`count(*) filter (where ${bookingFeedbacks.score} = 3)`, score4: sql<number>`count(*) filter (where ${bookingFeedbacks.score} = 4)`, score5: sql<number>`count(*) filter (where ${bookingFeedbacks.score} = 5)` }).from(bookingFeedbacks).where(and(eq(bookingFeedbacks.companyId, input.companyId), gte(bookingFeedbacks.createdAt, from), lte(bookingFeedbacks.createdAt, now))),
      db.select({ id: bookingFeedbacks.id, bookingId: bookingFeedbacks.bookingId, score: bookingFeedbacks.score, createdAt: bookingFeedbacks.createdAt, clientName: clients.name, bookingStartTime: bookings.startTime }).from(bookingFeedbacks).innerJoin(bookings, eq(bookings.id, bookingFeedbacks.bookingId)).innerJoin(clients, eq(clients.id, bookingFeedbacks.clientId)).where(and(eq(bookingFeedbacks.companyId, input.companyId), lte(bookingFeedbacks.score, 2), gte(bookingFeedbacks.createdAt, from), lte(bookingFeedbacks.createdAt, now), eq(bookings.companyId, input.companyId))).orderBy(desc(bookingFeedbacks.createdAt)).limit(20),
    ]); const row = summaryRows[0]; return { periodDays: days, summary: { total: Number(row?.total ?? 0), average: Number(Number(row?.average ?? 0).toFixed(1)), distribution: [1, 2, 3, 4, 5].map((score) => ({ score, count: Number((row as any)?.["score" + score] ?? 0) })) }, recovery: recovery.map((item) => ({ ...item, createdAt: item.createdAt.toISOString(), bookingStartTime: item.bookingStartTime.toISOString() })) };
  }
}
