"use client";
import { useEffect, useState } from "react";
import { Building2, Plus, Save, X } from "lucide-react";
import { ActionFeedback } from "@/components/ui/ActionFeedback";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SisagDataState, SisagPage, SisagPageHeader } from "@/components/sisag";
import { CompanyUnitCards, type CompanyUnitView } from "@/components/units/CompanyUnitCards";

type Form = Omit<CompanyUnitView, "id">;
const emptyForm: Form = { code: "", name: "", timeZone: "America/Sao_Paulo", phone: null, email: null, postalCode: null, street: null, number: null, complement: null, district: null, city: null, state: null, countryCode: "BR", isDefault: false, active: true };

export default function CompanyUnitsPage() {
  const [items, setItems] = useState<CompanyUnitView[]>([]); const [form, setForm] = useState<Form>(emptyForm);
  const [editingId, setEditingId] = useState<string | null>(null); const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [loadError, setLoadError] = useState(false);
  const [feedback, setFeedback] = useState<{ type: "success" | "error" | "info"; message: string } | null>(null);
  const field = <K extends keyof Form>(key: K, value: Form[K]) => setForm((current) => ({ ...current, [key]: value }));

  async function load() { setLoading(true); setLoadError(false); try { const response = await fetch("/api/v1/me/company/units", { cache: "no-store" }); const body = await response.json().catch(() => null); if (!response.ok || body?.ok !== true) throw new Error("load"); setItems(body.items ?? []); } catch { setLoadError(true); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  function startNew() { setEditingId(null); setForm({ ...emptyForm, isDefault: items.length === 0 }); setShowForm(true); setFeedback(null); }
  function startEdit(item: CompanyUnitView) { const { id, ...value } = item; setEditingId(id); setForm(value); setShowForm(true); setFeedback(null); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function cancel() { setShowForm(false); setEditingId(null); setForm(emptyForm); }
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setFeedback(null); try { const response = await fetch(editingId ? `/api/v1/me/company/units/${editingId}` : "/api/v1/me/company/units", { method: editingId ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json().catch(() => null); if (!response.ok || body?.ok !== true) { setFeedback({ type: "error", message: body?.message ?? "Revise os campos informados." }); return; } await load(); cancel(); setFeedback({ type: "success", message: editingId ? "Unidade atualizada com sucesso." : "Unidade criada com sucesso." }); } catch { setFeedback({ type: "error", message: "Não foi possível salvar a unidade." }); } finally { setSaving(false); } }
  if (loading) return <SisagPage><SisagDataState state="loading" title="Carregando unidades" /></SisagPage>;
  if (loadError) return <SisagPage><SisagDataState state="error" title="Não foi possível carregar as unidades" action={<Button variant="outline" onClick={() => void load()}>Tentar novamente</Button>} /></SisagPage>;
  return <SisagPage><SisagPageHeader context={<span className="inline-flex items-center gap-2"><Building2 className="h-4 w-4" />Estrutura de atendimento</span>} title="Unidades" description="Organize os locais onde sua equipe realiza os atendimentos." actions={<Button onClick={startNew}><Plus className="mr-2 h-4 w-4" />Nova unidade</Button>} />
    {feedback ? <ActionFeedback type={feedback.type} message={feedback.message} /> : null}
    {showForm ? <Card className="rounded-2xl border-slate-200 shadow-sm"><CardHeader><CardTitle>{editingId ? "Editar unidade" : "Nova unidade"}</CardTitle><CardDescription>Informe a identidade, o contato e o endereço do local de atendimento.</CardDescription></CardHeader><CardContent><form onSubmit={save} className="space-y-6"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">
      <div className="space-y-2 lg:col-span-2"><Label htmlFor="unit-name">Nome da unidade *</Label><Input id="unit-name" value={form.name} onChange={(e) => field("name", e.target.value)} required minLength={2} /></div><div className="space-y-2"><Label htmlFor="unit-code">Código *</Label><Input id="unit-code" value={form.code} onChange={(e) => field("code", e.target.value.toLowerCase().replace(/[^a-z0-9_-]/g, ""))} required minLength={2} /><p className="text-xs text-slate-500">Identificador curto, como centro ou zona-sul.</p></div>
      <div className="space-y-2"><Label htmlFor="postal">CEP / código postal</Label><Input id="postal" value={form.postalCode ?? ""} onChange={(e) => field("postalCode", e.target.value || null)} /></div><div className="space-y-2 lg:col-span-2"><Label htmlFor="street">Logradouro</Label><Input id="street" value={form.street ?? ""} onChange={(e) => field("street", e.target.value || null)} /></div><div className="space-y-2"><Label htmlFor="number">Número</Label><Input id="number" value={form.number ?? ""} onChange={(e) => field("number", e.target.value || null)} /></div><div className="space-y-2"><Label htmlFor="complement">Complemento</Label><Input id="complement" value={form.complement ?? ""} onChange={(e) => field("complement", e.target.value || null)} /></div><div className="space-y-2"><Label htmlFor="district">Bairro</Label><Input id="district" value={form.district ?? ""} onChange={(e) => field("district", e.target.value || null)} /></div><div className="space-y-2"><Label htmlFor="city">Cidade</Label><Input id="city" value={form.city ?? ""} onChange={(e) => field("city", e.target.value || null)} /></div><div className="space-y-2"><Label htmlFor="state">Estado / região</Label><Input id="state" value={form.state ?? ""} onChange={(e) => field("state", e.target.value || null)} /></div><div className="space-y-2"><Label htmlFor="country">País</Label><Input id="country" value={form.countryCode} onChange={(e) => field("countryCode", e.target.value.toUpperCase().slice(0, 2))} required maxLength={2} /></div>
      <div className="space-y-2"><Label htmlFor="phone">Telefone</Label><Input id="phone" value={form.phone ?? ""} onChange={(e) => field("phone", e.target.value || null)} /></div><div className="space-y-2"><Label htmlFor="email">E-mail</Label><Input id="email" type="email" value={form.email ?? ""} onChange={(e) => field("email", e.target.value || null)} /></div><div className="space-y-2"><Label htmlFor="timezone">Fuso horário *</Label><Input id="timezone" value={form.timeZone} onChange={(e) => field("timeZone", e.target.value)} required /></div>
      </div><div className="flex flex-wrap gap-6 rounded-xl bg-slate-50 p-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={(e) => field("active", e.target.checked)} />Unidade ativa</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isDefault} disabled={editingId !== null && form.isDefault} onChange={(e) => field("isDefault", e.target.checked)} />Unidade principal</label></div><div className="flex justify-end gap-3 border-t border-slate-100 pt-5"><Button type="button" variant="outline" onClick={cancel}><X className="mr-2 h-4 w-4" />Cancelar</Button><Button type="submit" disabled={saving}><Save className="mr-2 h-4 w-4" />{saving ? "Salvando..." : "Salvar unidade"}</Button></div></form></CardContent></Card> : null}
    <section className="space-y-3"><div><h2 className="text-lg font-semibold text-slate-950">Locais cadastrados</h2><p className="text-sm text-slate-500">{items.length} {items.length === 1 ? "unidade cadastrada" : "unidades cadastradas"}</p></div><CompanyUnitCards items={items} onEdit={startEdit} /></section>
  </SisagPage>;
}
