import { NextRequest, NextResponse } from "next/server";
import { requireApiRole } from "@/lib/auth/apiAuth";
import { ServiceBookingAssignmentFilterSchema, ServiceBookingAssignmentInputSchema } from "@/modules/scheduling-config/ServiceBookingAssignment.schema";
import { createServiceBookingAssignment, listServiceBookingAssignments, ServiceBookingAssignmentError } from "@/modules/scheduling-config/ServiceBookingAssignment.service";

const conflict = (error: unknown) => typeof error === "object" && error !== null && "code" in error && error.code === "23505";
function failure(error: unknown) { if (conflict(error)) return NextResponse.json({ ok: false, error: "assignment_conflict", message: "Já existe uma regra para este serviço e turno." }, { status: 409 }); if (error instanceof ServiceBookingAssignmentError) return NextResponse.json({ ok: false, error: error.code }, { status: error.code.endsWith("not_found") ? 404 : 400 }); console.error("service assignment API error", error); return NextResponse.json({ ok: false, error: "internal_error" }, { status: 500 }); }

export async function GET(request: NextRequest) { try { const auth = await requireApiRole(request, ["owner", "admin", "staff"]); if (auth.ok === false) return auth.response; const query = Object.fromEntries(new URL(request.url).searchParams); const parsed = ServiceBookingAssignmentFilterSchema.safeParse(query); if (!parsed.success) return NextResponse.json({ ok: false, error: "invalid_filter", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); return NextResponse.json({ ok: true, items: await listServiceBookingAssignments(auth.auth.companyId, parsed.data) }); } catch (error) { return failure(error); } }
export async function POST(request: NextRequest) { try { const auth = await requireApiRole(request, ["owner", "admin"]); if (auth.ok === false) return auth.response; const parsed = ServiceBookingAssignmentInputSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ ok: false, error: "invalid_assignment", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); const item = await createServiceBookingAssignment(auth.auth.companyId, parsed.data); return NextResponse.json({ ok: true, item }, { status: 201 }); } catch (error) { return failure(error); } }
