"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Plus, RotateCcw, Search, UserRound } from "lucide-react";
import { ActionFeedback } from "@/components/ui/ActionFeedback";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { SisagDataState, SisagPage, SisagPageHeader } from "@/components/sisag";
type Professional = { id: string; name: string; specialty: string | null; status: string | null; avgDuration: number | null };
type StatusFilter = "active" | "inactive" | "all";
const inactive = (status: string | null) => status === "INACTIVE" || status === "inactive";
export default function ProfessionalsPage() {
  const [items, setItems] = useState<Professional[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState<StatusFilter>("active"); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(false); const [reactivating, setReactivating] = useState(""); const [feedback, setFeedback] = useState<{ type: "success" | "error" | "info"; message: string } | null>(null);
  async function load(term = search, selectedStatus = status) { setLoading(true); setLoadError(false); try { const params = new URLSearchParams({ status: selectedStatus }); if (term.trim()) params.set("search", term.trim()); const response = await fetch("/api/v1/professionals?" + params.toString(), { cache: "no-store" }); const body = await response.json().catch(() => null); if (!response.ok || body?.ok !== true) throw new Error("load"); setItems(body.items ?? []); } catch { setLoadError(true); } finally { setLoading(false); } }
  useEffect(() => { void load("", "active"); }, []);
  function changeStatus(value: StatusFilter) { setStatus(value); setFeedback(null); void load(search, value); }
  async function reactivate(item: Professional) { setReactivating(item.id); setFeedback(null); try { const response = await fetch("/api/v1/professionals/" + item.id, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: item.name, specialty: item.specialty, status: "ACTIVE", avgDuration: item.avgDuration ?? 20 }) }); if (!response.ok) throw new Error("reactivate"); setFeedback({ type: "success", message: item.name + " foi reativado e voltou a ficar disponível para configuração." }); await load(search, status); } catch { setFeedback({ type: "error", message: "Não foi possível reativar o profissional." }); } finally { setReactivating(""); } }
  if (loading && items.length === 0) return <SisagPage><SisagDataState state="loading" title="Carregando profissionais" /></SisagPage>;
  if (loadError && items.length === 0) return <SisagPage><SisagDataState state="error" title="Não foi possível carregar os profissionais" action={<Button variant="outline" onClick={() => void load()}>Tentar novamente</Button>} /></SisagPage>;
  return <SisagPage><SisagPageHeader context={<span className="inline-flex items-center gap-2"><UserRound className="h-4 w-4" />Equipe de atendimento</span>} title="Profissionais" description="Organize quem atende, seus locais e o tempo médio dos serviços." actions={<Button asChild><Link href="/admin/professionals/new"><Plus className="mr-2 h-4 w-4" />Adicionar profissional</Link></Button>} />
    {feedback ? <ActionFeedback type={feedback.type} message={feedback.message} /> : null}
    <Card className="rounded-2xl border-slate-200 shadow-sm"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void load(search, status); }} className="pl-9" placeholder="Buscar por nome" /></div><select aria-label="Filtrar por situação" value={status} onChange={(event) => changeStatus(event.target.value as StatusFilter)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="all">Todos</option></select><Button variant="outline" onClick={() => void load(search, status)}>Buscar</Button></CardContent></Card>
    {items.length === 0 ? <SisagDataState state="empty" title={status === "active" ? "Nenhum profissional ativo" : status === "inactive" ? "Nenhum profissional inativo" : "Nenhum profissional cadastrado"} description={status === "inactive" ? "Profissionais desativados aparecerão aqui e poderão ser reativados." : "Adicione um profissional ou ajuste os filtros."} action={status === "active" ? <Button asChild><Link href="/admin/professionals/new">Adicionar profissional</Link></Button> : undefined} /> : <div className="grid gap-4 lg:grid-cols-2">{items.map((item) => <Card key={item.id} className="rounded-2xl border-slate-200 shadow-sm"><CardContent className="flex h-full flex-col justify-between gap-5 p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold text-slate-950">{item.name}</h2><p className="mt-1 text-sm text-slate-500">{item.specialty || "Função não informada"}</p></div><span className={inactive(item.status) ? "rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-600" : "rounded-full bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-700"}>{inactive(item.status) ? "Inativo" : "Ativo"}</span></div><div className="flex flex-col gap-3 border-t border-slate-100 pt-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-500">Atendimento médio: <strong className="text-slate-700">{item.avgDuration ?? 20} min</strong></p><div className="flex gap-2">{inactive(item.status) ? <Button type="button" variant="outline" size="sm" disabled={reactivating === item.id} onClick={() => void reactivate(item)}><RotateCcw className="mr-2 h-4 w-4" />{reactivating === item.id ? "Reativando..." : "Reativar"}</Button> : null}<Button asChild variant="outline" size="sm"><Link href={"/admin/professionals/" + item.id + "/availability"}>Disponibilidade</Link></Button><Button asChild variant="outline" size="sm"><Link href={"/admin/professionals/" + item.id + "/services"}>Configurar serviços</Link></Button><Button asChild variant="outline" size="sm"><Link href={"/admin/professionals/" + item.id + "/edit"}>Editar cadastro</Link></Button></div></div></CardContent></Card>)}</div>}
  </SisagPage>;
}
