"use client";
import { useEffect, useMemo, useState } from "react";
import { CalendarOff, Plus, RotateCcw } from "lucide-react";
import { ActionFeedback } from "@/components/ui/ActionFeedback";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SisagDataState, SisagPage, SisagPageHeader } from "@/components/sisag";
import { AVAILABILITY_EXCEPTION_KIND, exceptionScope, toExceptionPeriod, type ExceptionKind } from "@/modules/availability/AvailabilityException.presentation";
type Unit = { id: string; name: string; active: boolean }; type Professional = { id: string; name: string }; type Item = { id: string; kind: ExceptionKind; unitId: string | null; unitName: string | null; professionalId: string | null; professionalName: string | null; startsAt: string; endsAt: string; allDay: boolean; reason: string; status: string; revokedAt: string | null }; type Feedback = { type: "success" | "error" | "info"; message: string };
const today = () => new Date().toISOString().slice(0, 10);
export default function AvailabilityExceptionsPage() { const [units, setUnits] = useState<Unit[]>([]); const [professionals, setProfessionals] = useState<Professional[]>([]); const [items, setItems] = useState<Item[]>([]); const [kind, setKind] = useState<ExceptionKind>("holiday"); const [unitId, setUnitId] = useState(""); const [professionalId, setProfessionalId] = useState(""); const [allDay, setAllDay] = useState(true); const [start, setStart] = useState(today()); const [end, setEnd] = useState(today()); const [reason, setReason] = useState(""); const [status, setStatus] = useState<"active" | "revoked" | "all">("active"); const [filterUnit, setFilterUnit] = useState(""); const [filterProfessional, setFilterProfessional] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [pendingRevoke, setPendingRevoke] = useState(""); const [revoking, setRevoking] = useState(""); const [feedback, setFeedback] = useState<Feedback | null>(null); const needsProfessional = kind === "absence" || kind === "block";
  const visibleProfessionals = useMemo(() => professionals, [professionals]);
  async function loadExceptions(nextStatus = status, nextUnit = filterUnit, nextProfessional = filterProfessional) { const query = new URLSearchParams({ status: nextStatus }); if (nextUnit) query.set("unitId", nextUnit); if (nextProfessional) query.set("professionalId", nextProfessional); const response = await fetch("/api/v1/availability/exceptions?" + query.toString(), { cache: "no-store" }); const body = await response.json().catch(() => null); if (!response.ok || body?.ok !== true) throw new Error("exceptions"); setItems(body.items ?? []); }
  useEffect(() => { void (async () => { setLoading(true); try { const [unitResponse, professionalResponse] = await Promise.all([fetch("/api/v1/me/company/units"), fetch("/api/v1/professionals?status=active")]); const unitBody = await unitResponse.json(); const professionalBody = await professionalResponse.json(); if (unitBody?.ok !== true || professionalBody?.ok !== true) throw new Error("references"); setUnits((unitBody.items ?? []).filter((item: Unit) => item.active)); setProfessionals(professionalBody.items ?? []); await loadExceptions("active", "", ""); } catch { setFeedback({ type: "error", message: "Não foi possível carregar feriados e bloqueios." }); } finally { setLoading(false); } })(); }, []);
  function changeKind(value: ExceptionKind) { setKind(value); if (value === "holiday" || value === "closure") setProfessionalId(""); }
  async function create() { setSaving(true); setFeedback(null); try { if (needsProfessional && !professionalId) throw new Error("Selecione o profissional."); const period = toExceptionPeriod(start, end, allDay); const response = await fetch("/api/v1/availability/exceptions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind, unitId: unitId || null, professionalId: needsProfessional ? professionalId : null, ...period, allDay, reason }) }); const body = await response.json().catch(() => null); if (!response.ok) { if (body?.error === "professional_unit_not_linked") throw new Error("O profissional não atende no local selecionado."); throw new Error("Revise o período, o motivo e a abrangência."); } setReason(""); await loadExceptions(); setFeedback({ type: "success", message: "Exceção adicionada e já considerada no cálculo de horários." }); } catch (error) { setFeedback({ type: "error", message: error instanceof Error ? error.message : "Não foi possível salvar." }); } finally { setSaving(false); } }
  async function revoke(id: string) { if (pendingRevoke !== id) { setPendingRevoke(id); setFeedback({ type: "info", message: "Clique novamente em Revogar para confirmar." }); return; } setRevoking(id); try { const response = await fetch("/api/v1/availability/exceptions/" + id + "/revoke", { method: "POST" }); if (!response.ok) throw new Error("revoke"); setPendingRevoke(""); await loadExceptions(); setFeedback({ type: "success", message: "Exceção revogada. O histórico foi preservado." }); } catch { setFeedback({ type: "error", message: "Não foi possível revogar esta exceção." }); } finally { setRevoking(""); } }
  async function applyFilters(nextStatus = status) { setStatus(nextStatus); try { await loadExceptions(nextStatus, filterUnit, filterProfessional); } catch { setFeedback({ type: "error", message: "Não foi possível aplicar os filtros." }); } }
  if (loading) return <SisagPage><SisagDataState state="loading" title="Carregando feriados e bloqueios" /></SisagPage>;
  return <SisagPage><SisagPageHeader context={<span className="inline-flex items-center gap-2"><CalendarOff className="h-4 w-4" />Disponibilidade</span>} title="Feriados, ausências e bloqueios" description="Suspenda horários sem apagar a agenda semanal. Toda revogação permanece no histórico." />{feedback ? <ActionFeedback type={feedback.type} message={feedback.message} /> : null}
    <Card className="rounded-2xl border-slate-200 shadow-sm"><CardHeader><CardTitle className="text-lg">Adicionar exceção</CardTitle><CardDescription>Escolha o motivo, a abrangência e o período que não deverá receber agendamentos.</CardDescription></CardHeader><CardContent className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><div><Label>Tipo</Label><select value={kind} onChange={(event) => changeKind(event.target.value as ExceptionKind)} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{Object.entries(AVAILABILITY_EXCEPTION_KIND).map(([value, item]) => <option key={value} value={value}>{item.label}</option>)}</select><p className="mt-1 text-xs text-slate-500">{AVAILABILITY_EXCEPTION_KIND[kind].description}</p></div><div><Label>Local</Label><select value={unitId} onChange={(event) => setUnitId(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Toda a empresa</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></div>{needsProfessional ? <div><Label>Profissional</Label><select value={professionalId} onChange={(event) => setProfessionalId(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Selecione</option>{visibleProfessionals.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div> : null}<div className="flex items-center"><label className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" checked={allDay} onChange={(event) => { setAllDay(event.target.checked); setStart(today()); setEnd(today()); }} /><span className="text-sm font-medium">Dia inteiro</span></label></div><div><Label>Início</Label><Input className="mt-1" type={allDay ? "date" : "datetime-local"} value={start} onChange={(event) => setStart(event.target.value)} /></div><div><Label>{allDay ? "Último dia" : "Fim"}</Label><Input className="mt-1" type={allDay ? "date" : "datetime-local"} value={end} onChange={(event) => setEnd(event.target.value)} /></div><div className="md:col-span-2"><Label>Motivo</Label><Input className="mt-1" maxLength={240} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Ex.: feriado municipal, férias ou manutenção" /></div><div className="md:col-span-2 xl:col-span-4 flex justify-end"><Button onClick={() => void create()} disabled={saving || reason.trim().length < 2}><Plus className="mr-2 h-4 w-4" />{saving ? "Adicionando..." : "Adicionar exceção"}</Button></div></CardContent></Card>
    <Card className="rounded-2xl border-slate-200"><CardContent className="grid gap-3 p-4 md:grid-cols-4"><select aria-label="Situação" value={status} onChange={(event) => void applyFilters(event.target.value as typeof status)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="active">Ativas</option><option value="revoked">Revogadas</option><option value="all">Todas</option></select><select aria-label="Filtrar por local" value={filterUnit} onChange={(event) => setFilterUnit(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="">Todos os locais</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select><select aria-label="Filtrar por profissional" value={filterProfessional} onChange={(event) => setFilterProfessional(event.target.value)} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="">Todos os profissionais</option>{professionals.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Button variant="outline" onClick={() => void applyFilters()}>Aplicar filtros</Button></CardContent></Card>
    {items.length === 0 ? <SisagDataState state="empty" title="Nenhuma exceção encontrada" description="A disponibilidade semanal seguirá normalmente para este filtro." /> : <div className="grid gap-4 lg:grid-cols-2">{items.map((item) => <Card key={item.id} className="rounded-2xl border-slate-200"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-base">{AVAILABILITY_EXCEPTION_KIND[item.kind].label}</CardTitle><CardDescription>{exceptionScope(item)}</CardDescription></div><span className={item.status === "active" ? "rounded-full bg-amber-50 px-3 py-1 text-xs font-medium text-amber-700" : "rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-600"}>{item.status === "active" ? "Ativa" : "Revogada"}</span></div></CardHeader><CardContent className="space-y-3"><div><p className="font-medium text-slate-900">{new Date(item.startsAt).toLocaleString("pt-BR")} até {new Date(item.endsAt).toLocaleString("pt-BR")}</p><p className="mt-1 text-sm text-slate-600">{item.reason}</p></div>{item.status === "active" ? <div className="flex justify-end border-t border-slate-100 pt-3"><Button variant={pendingRevoke === item.id ? "destructive" : "outline"} size="sm" disabled={revoking === item.id} onClick={() => void revoke(item.id)}><RotateCcw className="mr-2 h-4 w-4" />{revoking === item.id ? "Revogando..." : pendingRevoke === item.id ? "Confirmar revogação" : "Revogar"}</Button></div> : null}</CardContent></Card>)}</div>}
  </SisagPage>;
}
