import { and, asc, eq, inArray } from "drizzle-orm";
import { getDb } from "@/lib/db";
import { professionals, whatsappAccounts, whatsappStaffAccessAudit, whatsappStaffAccesses } from "@/drizzle/schema";
import { normalizePhoneE164 } from "@/modules/clients/phone/normalizePhone";
import type { WhatsAppStaffAccessCreate, WhatsAppStaffAccessUpdate } from "./WhatsAppStaffAccessManagement.schema";

export class WhatsAppStaffAccessError extends Error { constructor(readonly code:"account_not_found"|"professional_not_found"|"access_not_found"|"duplicate_phone"){super(code)} }
export function prepareWhatsAppStaffAccess<T extends WhatsAppStaffAccessCreate|WhatsAppStaffAccessUpdate>(input:T){return{...input,phoneE164:normalizePhoneE164(input.phoneE164),professionalId:input.role==="manager"?null:input.professionalId!}}
async function validateScope(tx:any,companyId:string,input:{whatsappAccountId:string;role:string;professionalId?:string|null}){
 const account=await tx.select({id:whatsappAccounts.id}).from(whatsappAccounts).where(and(eq(whatsappAccounts.id,input.whatsappAccountId),eq(whatsappAccounts.companyId,companyId),eq(whatsappAccounts.status,"active"))).limit(1);if(!account[0])throw new WhatsAppStaffAccessError("account_not_found");
 if(input.role==="professional"){const p=await tx.select({id:professionals.id}).from(professionals).where(and(eq(professionals.id,input.professionalId!),eq(professionals.companyId,companyId),inArray(professionals.status,["active","ACTIVE"]))).limit(1);if(!p[0])throw new WhatsAppStaffAccessError("professional_not_found")}
}
export class WhatsAppStaffAccessManagementService{
 static async list(companyId:string){return getDb().select({id:whatsappStaffAccesses.id,whatsappAccountId:whatsappStaffAccesses.whatsappAccountId,phoneE164:whatsappStaffAccesses.phoneE164,role:whatsappStaffAccesses.role,professionalId:whatsappStaffAccesses.professionalId,professionalName:professionals.name,active:whatsappStaffAccesses.active,createdAt:whatsappStaffAccesses.createdAt,updatedAt:whatsappStaffAccesses.updatedAt}).from(whatsappStaffAccesses).leftJoin(professionals,and(eq(professionals.id,whatsappStaffAccesses.professionalId),eq(professionals.companyId,companyId))).where(eq(whatsappStaffAccesses.companyId,companyId)).orderBy(asc(whatsappStaffAccesses.phoneE164))}
 static async options(companyId:string){const db=getDb();const [accounts,professionalItems]=await Promise.all([db.select({id:whatsappAccounts.id,provider:whatsappAccounts.provider}).from(whatsappAccounts).where(and(eq(whatsappAccounts.companyId,companyId),eq(whatsappAccounts.status,"active"))).orderBy(asc(whatsappAccounts.createdAt)),db.select({id:professionals.id,name:professionals.name}).from(professionals).where(and(eq(professionals.companyId,companyId),inArray(professionals.status,["active","ACTIVE"]))).orderBy(asc(professionals.name))]);return{accounts,professionals:professionalItems}}
 static async create(input:{companyId:string;actorId:string;data:WhatsAppStaffAccessCreate}){const data=prepareWhatsAppStaffAccess(input.data),db=getDb();try{return await db.transaction(async tx=>{await validateScope(tx,input.companyId,data);const rows=await tx.insert(whatsappStaffAccesses).values({companyId:input.companyId,...data,createdBy:input.actorId,updatedBy:input.actorId}).returning();const item=rows[0]!;await tx.insert(whatsappStaffAccessAudit).values({companyId:input.companyId,accessId:item.id,action:"created",actorId:input.actorId,snapshot:item});return item})}catch(error:any){if(error?.code==="23505")throw new WhatsAppStaffAccessError("duplicate_phone");throw error}}
 static async update(input:{companyId:string;actorId:string;data:WhatsAppStaffAccessUpdate}){const data=prepareWhatsAppStaffAccess(input.data),db=getDb();try{return await db.transaction(async tx=>{await validateScope(tx,input.companyId,data);const current=await tx.select({active:whatsappStaffAccesses.active}).from(whatsappStaffAccesses).where(and(eq(whatsappStaffAccesses.id,data.id),eq(whatsappStaffAccesses.companyId,input.companyId))).limit(1);if(!current[0])throw new WhatsAppStaffAccessError("access_not_found");const rows=await tx.update(whatsappStaffAccesses).set({whatsappAccountId:data.whatsappAccountId,phoneE164:data.phoneE164,role:data.role,professionalId:data.professionalId,active:data.active,updatedBy:input.actorId,updatedAt:new Date()}).where(and(eq(whatsappStaffAccesses.id,data.id),eq(whatsappStaffAccesses.companyId,input.companyId))).returning();const item=rows[0]!;const action=current[0].active&&!item.active?"deactivated":!current[0].active&&item.active?"reactivated":"updated";await tx.insert(whatsappStaffAccessAudit).values({companyId:input.companyId,accessId:item.id,action,actorId:input.actorId,snapshot:item});return item})}catch(error:any){if(error?.code==="23505")throw new WhatsAppStaffAccessError("duplicate_phone");throw error}}
}
